/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

public static class timConstants
{
  /// <summary>
  /// 内部版本号
  /// </summary>
  public const int protocolversion = 4;
  /// <summary>
  /// 外部版本号
  /// </summary>
  public const string protocolversionName = "1.1.0";
  /// <summary>
  /// 状态码：成功
  /// </summary>
  public const string TIM_SC_SUCCESS = "200";
  /// <summary>
  /// 状态码：失败
  /// </summary>
  public const string TIM_SC_FAILED = "400";
}
