<?php
/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class Constant extends \Thrift\Type\TConstant
{
    static protected $protocolversion;
    static protected $protocolversionName;
    static protected $TIM_SC_SUCCESS;
    static protected $TIM_SC_FAILED;

    protected static function init_protocolversion()
    {
        return         /**
         * 内部版本号
         */
4;
    }

    protected static function init_protocolversionName()
    {
        return         /**
         * 外部版本号
         */
"1.1.0";
    }

    protected static function init_TIM_SC_SUCCESS()
    {
        return         /**
         * 状态码：成功
         */
"200";
    }

    protected static function init_TIM_SC_FAILED()
    {
        return         /**
         * 状态码：失败
         */
"400";
    }
}
