<?php
/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class ITim_timResponsePresenceList_args
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'pbeanList',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\TimPBeanList',
        ),
        2 => array(
            'var' => 'auth',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\TimAuth',
        ),
    );

    /**
     * @var \TimPBeanList
     */
    public $pbeanList = null;
    /**
     * @var \TimAuth
     */
    public $auth = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['pbeanList'])) {
                $this->pbeanList = $vals['pbeanList'];
            }
            if (isset($vals['auth'])) {
                $this->auth = $vals['auth'];
            }
        }
    }

    public function getName()
    {
        return 'ITim_timResponsePresenceList_args';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->pbeanList = new \TimPBeanList();
                        $xfer += $this->pbeanList->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRUCT) {
                        $this->auth = new \TimAuth();
                        $xfer += $this->auth->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ITim_timResponsePresenceList_args');
        if ($this->pbeanList !== null) {
            if (!is_object($this->pbeanList)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('pbeanList', TType::STRUCT, 1);
            $xfer += $this->pbeanList->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->auth !== null) {
            if (!is_object($this->auth)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('auth', TType::STRUCT, 2);
            $xfer += $this->auth->write($output);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
