/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
module ITim;

import thrift.base;
import thrift.codegen.base;
import thrift.util.hashset;

import tim_types;

interface ITim {
  void timStream(ref const(TimParam) param);
  void timStarttls();
  void timLogin(ref const(Tid) tid, string pwd);
  void timAck(ref const(TimAckBean) ab);
  void timPresence(ref const(TimPBean) pbean);
  void timMessage(ref const(TimMBean) mbean);
  void timPing(string threadId);
  void timError(ref const(TimError) e);
  void timLogout();
  void timRegist(ref const(Tid) tid, string auth);
  void timRoser(ref const(TimRoster) roster);
  void timMessageList(ref const(TimMBeanList) mbeanList);
  void timPresenceList(ref const(TimPBeanList) pbeanList);
  void timMessageIq(ref const(TimMessageIq) timMsgIq, string iqType);
  void timMessageResult(ref const(TimMBean) mbean);
  void timProperty(ref const(TimPropertyBean) tpb);
  TimRemoteUserBean timRemoteUserAuth(ref const(Tid) tid, string pwd, ref const(TimAuth) auth);
  TimRemoteUserBean timRemoteUserGet(ref const(Tid) tid, ref const(TimAuth) auth);
  TimRemoteUserBean timRemoteUserEdit(ref const(Tid) tid, ref const(TimUserBean) ub, ref const(TimAuth) auth);
  TimResponseBean timResponsePresence(ref const(TimPBean) pbean, ref const(TimAuth) auth);
  TimResponseBean timResponseMessage(ref const(TimMBean) mbean, ref const(TimAuth) auth);
  TimMBeanList timResponseMessageIq(ref const(TimMessageIq) timMsgIq, string iqType, ref const(TimAuth) auth);
  TimResponseBean timResponsePresenceList(ref const(TimPBeanList) pbeanList, ref const(TimAuth) auth);
  TimResponseBean timResponseMessageList(ref const(TimMBeanList) mbeanList, ref const(TimAuth) auth);

  enum methodMeta = [
    TMethodMeta(`timStream`, 
      [TParamMeta(`param`, 1)],
      [],
      TMethodType.ONEWAY
    ),
    TMethodMeta(`timStarttls`, 
      [],
      [],
      TMethodType.ONEWAY
    ),
    TMethodMeta(`timLogin`, 
      [TParamMeta(`tid`, 1), TParamMeta(`pwd`, 2)],
      [],
      TMethodType.ONEWAY
    ),
    TMethodMeta(`timAck`, 
      [TParamMeta(`ab`, 1)],
      [],
      TMethodType.ONEWAY
    ),
    TMethodMeta(`timPresence`, 
      [TParamMeta(`pbean`, 1)],
      [],
      TMethodType.ONEWAY
    ),
    TMethodMeta(`timMessage`, 
      [TParamMeta(`mbean`, 1)],
      [],
      TMethodType.ONEWAY
    ),
    TMethodMeta(`timPing`, 
      [TParamMeta(`threadId`, 1)],
      [],
      TMethodType.ONEWAY
    ),
    TMethodMeta(`timError`, 
      [TParamMeta(`e`, 1)],
      [],
      TMethodType.ONEWAY
    ),
    TMethodMeta(`timLogout`, 
      [],
      [],
      TMethodType.ONEWAY
    ),
    TMethodMeta(`timRegist`, 
      [TParamMeta(`tid`, 1), TParamMeta(`auth`, 2)],
      [],
      TMethodType.ONEWAY
    ),
    TMethodMeta(`timRoser`, 
      [TParamMeta(`roster`, 1)],
      [],
      TMethodType.ONEWAY
    ),
    TMethodMeta(`timMessageList`, 
      [TParamMeta(`mbeanList`, 1)],
      [],
      TMethodType.ONEWAY
    ),
    TMethodMeta(`timPresenceList`, 
      [TParamMeta(`pbeanList`, 1)],
      [],
      TMethodType.ONEWAY
    ),
    TMethodMeta(`timMessageIq`, 
      [TParamMeta(`timMsgIq`, 1), TParamMeta(`iqType`, 2)],
      [],
      TMethodType.ONEWAY
    ),
    TMethodMeta(`timMessageResult`, 
      [TParamMeta(`mbean`, 1)],
      [],
      TMethodType.ONEWAY
    ),
    TMethodMeta(`timProperty`, 
      [TParamMeta(`tpb`, 1)],
      [],
      TMethodType.ONEWAY
    ),
    TMethodMeta(`timRemoteUserAuth`, 
      [TParamMeta(`tid`, 1), TParamMeta(`pwd`, 2), TParamMeta(`auth`, 3)]
    ),
    TMethodMeta(`timRemoteUserGet`, 
      [TParamMeta(`tid`, 1), TParamMeta(`auth`, 2)]
    ),
    TMethodMeta(`timRemoteUserEdit`, 
      [TParamMeta(`tid`, 1), TParamMeta(`ub`, 2), TParamMeta(`auth`, 3)]
    ),
    TMethodMeta(`timResponsePresence`, 
      [TParamMeta(`pbean`, 1), TParamMeta(`auth`, 2)]
    ),
    TMethodMeta(`timResponseMessage`, 
      [TParamMeta(`mbean`, 1), TParamMeta(`auth`, 2)]
    ),
    TMethodMeta(`timResponseMessageIq`, 
      [TParamMeta(`timMsgIq`, 1), TParamMeta(`iqType`, 2), TParamMeta(`auth`, 3)]
    ),
    TMethodMeta(`timResponsePresenceList`, 
      [TParamMeta(`pbeanList`, 1), TParamMeta(`auth`, 2)]
    ),
    TMethodMeta(`timResponseMessageList`, 
      [TParamMeta(`mbeanList`, 1), TParamMeta(`auth`, 2)]
    )
  ];
}
