/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TIM_TYPES_H
#define TIM_TYPES_H

/* base includes */
#include <glib-object.h>
#include <thrift/c_glib/thrift_struct.h>
#include <thrift/c_glib/protocol/thrift_protocol.h>

/* custom thrift includes */

/* begin types */

/* struct TimError */
struct _TimError
{ 
  ThriftStruct parent; 

  /* public */
  gint32 errCode;
  gboolean __isset_errCode;
  gchar * errMsg;
  gboolean __isset_errMsg;
};
typedef struct _TimError TimError;

struct _TimErrorClass
{
  ThriftStructClass parent;
};
typedef struct _TimErrorClass TimErrorClass;

GType tim_error_get_type (void);
#define TYPE_TIM_ERROR (tim_error_get_type())
#define TIM_ERROR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_ERROR, TimError))
#define TIM_ERROR_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_ERROR, TimErrorClass))
#define IS_TIM_ERROR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_ERROR))
#define IS_TIM_ERROR_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_ERROR))
#define TIM_ERROR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_ERROR, TimErrorClass))

/* struct TimNode */
struct _TimNode
{ 
  ThriftStruct parent; 

  /* public */
  gchar * key;
  gboolean __isset_key;
  gchar * value;
  gboolean __isset_value;
};
typedef struct _TimNode TimNode;

struct _TimNodeClass
{
  ThriftStructClass parent;
};
typedef struct _TimNodeClass TimNodeClass;

GType tim_node_get_type (void);
#define TYPE_TIM_NODE (tim_node_get_type())
#define TIM_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_NODE, TimNode))
#define TIM_NODE_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_NODE, TimNodeClass))
#define IS_TIM_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_NODE))
#define IS_TIM_NODE_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_NODE))
#define TIM_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_NODE, TimNodeClass))

/* struct TimAckBean */
struct _TimAckBean
{ 
  ThriftStruct parent; 

  /* public */
  gchar * id;
  gboolean __isset_id;
  gchar * ackType;
  gboolean __isset_ackType;
  gchar * ackStatus;
  gboolean __isset_ackStatus;
  GPtrArray * extraList;
  gboolean __isset_extraList;
  TimError * err;
  gboolean __isset_err;
  GHashTable * extraMap;
  gboolean __isset_extraMap;
};
typedef struct _TimAckBean TimAckBean;

struct _TimAckBeanClass
{
  ThriftStructClass parent;
};
typedef struct _TimAckBeanClass TimAckBeanClass;

GType tim_ack_bean_get_type (void);
#define TYPE_TIM_ACK_BEAN (tim_ack_bean_get_type())
#define TIM_ACK_BEAN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_ACK_BEAN, TimAckBean))
#define TIM_ACK_BEAN_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_ACK_BEAN, TimAckBeanClass))
#define IS_TIM_ACK_BEAN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_ACK_BEAN))
#define IS_TIM_ACK_BEAN_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_ACK_BEAN))
#define TIM_ACK_BEAN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_ACK_BEAN, TimAckBeanClass))

/* struct TimHBean */
struct _TimHBean
{ 
  ThriftStruct parent; 

  /* public */
  gint32 chl;
  gint32 platform;
  gboolean __isset_platform;
  gint16 version;
};
typedef struct _TimHBean TimHBean;

struct _TimHBeanClass
{
  ThriftStructClass parent;
};
typedef struct _TimHBeanClass TimHBeanClass;

GType tim_h_bean_get_type (void);
#define TYPE_TIM_H_BEAN (tim_h_bean_get_type())
#define TIM_H_BEAN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_H_BEAN, TimHBean))
#define TIM_H_BEAN_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_H_BEAN, TimHBeanClass))
#define IS_TIM_H_BEAN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_H_BEAN))
#define IS_TIM_H_BEAN_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_H_BEAN))
#define TIM_H_BEAN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_H_BEAN, TimHBeanClass))

/* struct TimParam */
struct _TimParam
{ 
  ThriftStruct parent; 

  /* public */
  gchar * timestamp;
  gboolean __isset_timestamp;
  gint16 version;
  gboolean __isset_version;
  gchar * lang;
  gboolean __isset_lang;
  GPtrArray * extraList;
  gboolean __isset_extraList;
  GHashTable * extraMap;
  gboolean __isset_extraMap;
  gchar * interflow;
  gboolean __isset_interflow;
  gchar * tls;
  gboolean __isset_tls;
};
typedef struct _TimParam TimParam;

struct _TimParamClass
{
  ThriftStructClass parent;
};
typedef struct _TimParamClass TimParamClass;

GType tim_param_get_type (void);
#define TYPE_TIM_PARAM (tim_param_get_type())
#define TIM_PARAM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_PARAM, TimParam))
#define TIM_PARAM_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_PARAM, TimParamClass))
#define IS_TIM_PARAM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_PARAM))
#define IS_TIM_PARAM_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_PARAM))
#define TIM_PARAM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_PARAM, TimParamClass))

/* struct TimTime */
struct _TimTime
{ 
  ThriftStruct parent; 

  /* public */
  gchar * timestamp;
  gboolean __isset_timestamp;
  gchar * formattime;
  gboolean __isset_formattime;
};
typedef struct _TimTime TimTime;

struct _TimTimeClass
{
  ThriftStructClass parent;
};
typedef struct _TimTimeClass TimTimeClass;

GType tim_time_get_type (void);
#define TYPE_TIM_TIME (tim_time_get_type())
#define TIM_TIME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_TIME, TimTime))
#define TIM_TIME_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_TIME, TimTimeClass))
#define IS_TIM_TIME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_TIME))
#define IS_TIM_TIME_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_TIME))
#define TIM_TIME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_TIME, TimTimeClass))

/* struct TimArea */
struct _TimArea
{ 
  ThriftStruct parent; 

  /* public */
  gchar * country;
  gboolean __isset_country;
  gchar * province;
  gboolean __isset_province;
  gchar * city;
  gboolean __isset_city;
  GPtrArray * extraList;
  gboolean __isset_extraList;
  GHashTable * extraMap;
  gboolean __isset_extraMap;
};
typedef struct _TimArea TimArea;

struct _TimAreaClass
{
  ThriftStructClass parent;
};
typedef struct _TimAreaClass TimAreaClass;

GType tim_area_get_type (void);
#define TYPE_TIM_AREA (tim_area_get_type())
#define TIM_AREA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_AREA, TimArea))
#define TIM_AREA_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_AREA, TimAreaClass))
#define IS_TIM_AREA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_AREA))
#define IS_TIM_AREA_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_AREA))
#define TIM_AREA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_AREA, TimAreaClass))

/* struct Tid */
struct _Tid
{ 
  ThriftStruct parent; 

  /* public */
  gchar * name;
  gchar * domain;
  gboolean __isset_domain;
  gchar * resource;
  gboolean __isset_resource;
  gchar * type;
  gboolean __isset_type;
  GPtrArray * extraList;
  gboolean __isset_extraList;
  GHashTable * extraMap;
  gboolean __isset_extraMap;
};
typedef struct _Tid Tid;

struct _TidClass
{
  ThriftStructClass parent;
};
typedef struct _TidClass TidClass;

GType tid_get_type (void);
#define TYPE_TID (tid_get_type())
#define TID(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TID, Tid))
#define TID_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TID, TidClass))
#define IS_TID(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TID))
#define IS_TID_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TID))
#define TID_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TID, TidClass))

/* struct TimUserBean */
struct _TimUserBean
{ 
  ThriftStruct parent; 

  /* public */
  Tid * tid;
  gboolean __isset_tid;
  gchar * nickname;
  gboolean __isset_nickname;
  gchar * remarkname;
  gboolean __isset_remarkname;
  gchar * brithday;
  gboolean __isset_brithday;
  gint16 gender;
  gboolean __isset_gender;
  gchar * headurl;
  gboolean __isset_headurl;
  TimArea * area;
  gboolean __isset_area;
  GByteArray * headbyte;
  gboolean __isset_headbyte;
  GPtrArray * photoBytes;
  gboolean __isset_photoBytes;
  GPtrArray * extraList;
  gboolean __isset_extraList;
  GHashTable * extraMap;
  gboolean __isset_extraMap;
};
typedef struct _TimUserBean TimUserBean;

struct _TimUserBeanClass
{
  ThriftStructClass parent;
};
typedef struct _TimUserBeanClass TimUserBeanClass;

GType tim_user_bean_get_type (void);
#define TYPE_TIM_USER_BEAN (tim_user_bean_get_type())
#define TIM_USER_BEAN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_USER_BEAN, TimUserBean))
#define TIM_USER_BEAN_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_USER_BEAN, TimUserBeanClass))
#define IS_TIM_USER_BEAN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_USER_BEAN))
#define IS_TIM_USER_BEAN_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_USER_BEAN))
#define TIM_USER_BEAN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_USER_BEAN, TimUserBeanClass))

/* struct TimRoom */
struct _TimRoom
{ 
  ThriftStruct parent; 

  /* public */
  Tid * tid;
  gboolean __isset_tid;
  Tid * founderTid;
  gboolean __isset_founderTid;
  GPtrArray * HostsTid;
  gboolean __isset_HostsTid;
  GPtrArray * membersTid;
  gboolean __isset_membersTid;
  gchar * headurl;
  gboolean __isset_headurl;
  gchar * roomName;
  gboolean __isset_roomName;
  gchar * desc;
  gboolean __isset_desc;
  TimTime * createTime;
  gboolean __isset_createTime;
  GPtrArray * extraList;
  gboolean __isset_extraList;
  GHashTable * extraMap;
  gboolean __isset_extraMap;
};
typedef struct _TimRoom TimRoom;

struct _TimRoomClass
{
  ThriftStructClass parent;
};
typedef struct _TimRoomClass TimRoomClass;

GType tim_room_get_type (void);
#define TYPE_TIM_ROOM (tim_room_get_type())
#define TIM_ROOM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_ROOM, TimRoom))
#define TIM_ROOM_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_ROOM, TimRoomClass))
#define IS_TIM_ROOM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_ROOM))
#define IS_TIM_ROOM_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_ROOM))
#define TIM_ROOM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_ROOM, TimRoomClass))

/* struct TimPBean */
struct _TimPBean
{ 
  ThriftStruct parent; 

  /* public */
  gchar * threadId;
  Tid * fromTid;
  gboolean __isset_fromTid;
  Tid * toTid;
  gboolean __isset_toTid;
  gchar * status;
  gboolean __isset_status;
  gchar * type;
  gboolean __isset_type;
  gint32 priority;
  gboolean __isset_priority;
  gchar * show;
  gboolean __isset_show;
  Tid * leaguerTid;
  gboolean __isset_leaguerTid;
  GPtrArray * extraList;
  gboolean __isset_extraList;
  TimError * error;
  gboolean __isset_error;
  GHashTable * extraMap;
  gboolean __isset_extraMap;
};
typedef struct _TimPBean TimPBean;

struct _TimPBeanClass
{
  ThriftStructClass parent;
};
typedef struct _TimPBeanClass TimPBeanClass;

GType tim_p_bean_get_type (void);
#define TYPE_TIM_P_BEAN (tim_p_bean_get_type())
#define TIM_P_BEAN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_P_BEAN, TimPBean))
#define TIM_P_BEAN_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_P_BEAN, TimPBeanClass))
#define IS_TIM_P_BEAN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_P_BEAN))
#define IS_TIM_P_BEAN_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_P_BEAN))
#define TIM_P_BEAN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_P_BEAN, TimPBeanClass))

/* struct TimMBean */
struct _TimMBean
{ 
  ThriftStruct parent; 

  /* public */
  gchar * threadId;
  gchar * mid;
  gboolean __isset_mid;
  Tid * fromTid;
  gboolean __isset_fromTid;
  Tid * toTid;
  gboolean __isset_toTid;
  gchar * body;
  gboolean __isset_body;
  gchar * type;
  gboolean __isset_type;
  gint16 msgType;
  gboolean __isset_msgType;
  TimTime * offline;
  gboolean __isset_offline;
  Tid * leaguerTid;
  gboolean __isset_leaguerTid;
  GPtrArray * extraList;
  gboolean __isset_extraList;
  gchar * timestamp;
  gboolean __isset_timestamp;
  TimError * error;
  gboolean __isset_error;
  GHashTable * extraMap;
  gboolean __isset_extraMap;
  gint16 readstatus;
  gboolean __isset_readstatus;
};
typedef struct _TimMBean TimMBean;

struct _TimMBeanClass
{
  ThriftStructClass parent;
};
typedef struct _TimMBeanClass TimMBeanClass;

GType tim_m_bean_get_type (void);
#define TYPE_TIM_M_BEAN (tim_m_bean_get_type())
#define TIM_M_BEAN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_M_BEAN, TimMBean))
#define TIM_M_BEAN_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_M_BEAN, TimMBeanClass))
#define IS_TIM_M_BEAN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_M_BEAN))
#define IS_TIM_M_BEAN_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_M_BEAN))
#define TIM_M_BEAN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_M_BEAN, TimMBeanClass))

/* struct TimIqBean */
struct _TimIqBean
{ 
  ThriftStruct parent; 

  /* public */
  gchar * threadId;
  Tid * fromTid;
  gboolean __isset_fromTid;
  Tid * toTid;
  gboolean __isset_toTid;
  gchar * type;
  gboolean __isset_type;
  GPtrArray * extraList;
  gboolean __isset_extraList;
  TimError * error;
  gboolean __isset_error;
  GHashTable * extraMap;
  gboolean __isset_extraMap;
};
typedef struct _TimIqBean TimIqBean;

struct _TimIqBeanClass
{
  ThriftStructClass parent;
};
typedef struct _TimIqBeanClass TimIqBeanClass;

GType tim_iq_bean_get_type (void);
#define TYPE_TIM_IQ_BEAN (tim_iq_bean_get_type())
#define TIM_IQ_BEAN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_IQ_BEAN, TimIqBean))
#define TIM_IQ_BEAN_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_IQ_BEAN, TimIqBeanClass))
#define IS_TIM_IQ_BEAN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_IQ_BEAN))
#define IS_TIM_IQ_BEAN_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_IQ_BEAN))
#define TIM_IQ_BEAN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_IQ_BEAN, TimIqBeanClass))

/* struct TimRoster */
struct _TimRoster
{ 
  ThriftStruct parent; 

  /* public */
  gchar * subscription;
  Tid * tid;
  gchar * name;
  gboolean __isset_name;
  GHashTable * extraMap;
  gboolean __isset_extraMap;
};
typedef struct _TimRoster TimRoster;

struct _TimRosterClass
{
  ThriftStructClass parent;
};
typedef struct _TimRosterClass TimRosterClass;

GType tim_roster_get_type (void);
#define TYPE_TIM_ROSTER (tim_roster_get_type())
#define TIM_ROSTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_ROSTER, TimRoster))
#define TIM_ROSTER_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_ROSTER, TimRosterClass))
#define IS_TIM_ROSTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_ROSTER))
#define IS_TIM_ROSTER_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_ROSTER))
#define TIM_ROSTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_ROSTER, TimRosterClass))

/* struct TimRemoteUserBean */
struct _TimRemoteUserBean
{ 
  ThriftStruct parent; 

  /* public */
  TimError * error;
  gboolean __isset_error;
  TimUserBean * ub;
  gboolean __isset_ub;
  GHashTable * extraMap;
  gboolean __isset_extraMap;
};
typedef struct _TimRemoteUserBean TimRemoteUserBean;

struct _TimRemoteUserBeanClass
{
  ThriftStructClass parent;
};
typedef struct _TimRemoteUserBeanClass TimRemoteUserBeanClass;

GType tim_remote_user_bean_get_type (void);
#define TYPE_TIM_REMOTE_USER_BEAN (tim_remote_user_bean_get_type())
#define TIM_REMOTE_USER_BEAN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_REMOTE_USER_BEAN, TimRemoteUserBean))
#define TIM_REMOTE_USER_BEAN_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_REMOTE_USER_BEAN, TimRemoteUserBeanClass))
#define IS_TIM_REMOTE_USER_BEAN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_REMOTE_USER_BEAN))
#define IS_TIM_REMOTE_USER_BEAN_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_REMOTE_USER_BEAN))
#define TIM_REMOTE_USER_BEAN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_REMOTE_USER_BEAN, TimRemoteUserBeanClass))

/* struct TimRemoteRoom */
struct _TimRemoteRoom
{ 
  ThriftStruct parent; 

  /* public */
  TimError * error;
  gboolean __isset_error;
  TimRoom * room;
  gboolean __isset_room;
  GHashTable * extraMap;
  gboolean __isset_extraMap;
};
typedef struct _TimRemoteRoom TimRemoteRoom;

struct _TimRemoteRoomClass
{
  ThriftStructClass parent;
};
typedef struct _TimRemoteRoomClass TimRemoteRoomClass;

GType tim_remote_room_get_type (void);
#define TYPE_TIM_REMOTE_ROOM (tim_remote_room_get_type())
#define TIM_REMOTE_ROOM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_REMOTE_ROOM, TimRemoteRoom))
#define TIM_REMOTE_ROOM_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_REMOTE_ROOM, TimRemoteRoomClass))
#define IS_TIM_REMOTE_ROOM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_REMOTE_ROOM))
#define IS_TIM_REMOTE_ROOM_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_REMOTE_ROOM))
#define TIM_REMOTE_ROOM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_REMOTE_ROOM, TimRemoteRoomClass))

/* struct TimResponseBean */
struct _TimResponseBean
{ 
  ThriftStruct parent; 

  /* public */
  gchar * threadId;
  gboolean __isset_threadId;
  TimError * error;
  gboolean __isset_error;
  GPtrArray * extraList;
  gboolean __isset_extraList;
  GHashTable * extraMap;
  gboolean __isset_extraMap;
};
typedef struct _TimResponseBean TimResponseBean;

struct _TimResponseBeanClass
{
  ThriftStructClass parent;
};
typedef struct _TimResponseBeanClass TimResponseBeanClass;

GType tim_response_bean_get_type (void);
#define TYPE_TIM_RESPONSE_BEAN (tim_response_bean_get_type())
#define TIM_RESPONSE_BEAN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_RESPONSE_BEAN, TimResponseBean))
#define TIM_RESPONSE_BEAN_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_RESPONSE_BEAN, TimResponseBeanClass))
#define IS_TIM_RESPONSE_BEAN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_RESPONSE_BEAN))
#define IS_TIM_RESPONSE_BEAN_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_RESPONSE_BEAN))
#define TIM_RESPONSE_BEAN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_RESPONSE_BEAN, TimResponseBeanClass))

/* struct TimSock5Bean */
struct _TimSock5Bean
{ 
  ThriftStruct parent; 

  /* public */
  Tid * fromTid;
  Tid * toTid;
  gchar * addr;
  gint32 port;
  gint16 transport;
  gchar * pubId;
  GHashTable * extraMap;
  gboolean __isset_extraMap;
};
typedef struct _TimSock5Bean TimSock5Bean;

struct _TimSock5BeanClass
{
  ThriftStructClass parent;
};
typedef struct _TimSock5BeanClass TimSock5BeanClass;

GType tim_sock5_bean_get_type (void);
#define TYPE_TIM_SOCK5_BEAN (tim_sock5_bean_get_type())
#define TIM_SOCK5_BEAN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_SOCK5_BEAN, TimSock5Bean))
#define TIM_SOCK5_BEAN_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_SOCK5_BEAN, TimSock5BeanClass))
#define IS_TIM_SOCK5_BEAN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_SOCK5_BEAN))
#define IS_TIM_SOCK5_BEAN_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_SOCK5_BEAN))
#define TIM_SOCK5_BEAN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_SOCK5_BEAN, TimSock5BeanClass))

/* struct TimSock5Bytes */
struct _TimSock5Bytes
{ 
  ThriftStruct parent; 

  /* public */
  gchar * pubId;
  gint32 index;
  GPtrArray * bytes;
  GHashTable * extraMap;
  gboolean __isset_extraMap;
};
typedef struct _TimSock5Bytes TimSock5Bytes;

struct _TimSock5BytesClass
{
  ThriftStructClass parent;
};
typedef struct _TimSock5BytesClass TimSock5BytesClass;

GType tim_sock5_bytes_get_type (void);
#define TYPE_TIM_SOCK5_BYTES (tim_sock5_bytes_get_type())
#define TIM_SOCK5_BYTES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_SOCK5_BYTES, TimSock5Bytes))
#define TIM_SOCK5_BYTES_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_SOCK5_BYTES, TimSock5BytesClass))
#define IS_TIM_SOCK5_BYTES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_SOCK5_BYTES))
#define IS_TIM_SOCK5_BYTES_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_SOCK5_BYTES))
#define TIM_SOCK5_BYTES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_SOCK5_BYTES, TimSock5BytesClass))

/* struct TimPage */
struct _TimPage
{ 
  ThriftStruct parent; 

  /* public */
  gchar * fromTimeStamp;
  gboolean __isset_fromTimeStamp;
  gchar * toTimeStamp;
  gboolean __isset_toTimeStamp;
  gint32 limitCount;
  gboolean __isset_limitCount;
  GHashTable * extraMap;
  gboolean __isset_extraMap;
};
typedef struct _TimPage TimPage;

struct _TimPageClass
{
  ThriftStructClass parent;
};
typedef struct _TimPageClass TimPageClass;

GType tim_page_get_type (void);
#define TYPE_TIM_PAGE (tim_page_get_type())
#define TIM_PAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_PAGE, TimPage))
#define TIM_PAGE_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_PAGE, TimPageClass))
#define IS_TIM_PAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_PAGE))
#define IS_TIM_PAGE_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_PAGE))
#define TIM_PAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_PAGE, TimPageClass))

/* struct TimMessageIq */
struct _TimMessageIq
{ 
  ThriftStruct parent; 

  /* public */
  GPtrArray * tidlist;
  gboolean __isset_tidlist;
  TimPage * timPage;
  gboolean __isset_timPage;
  GPtrArray * midlist;
  gboolean __isset_midlist;
  GHashTable * extraMap;
  gboolean __isset_extraMap;
};
typedef struct _TimMessageIq TimMessageIq;

struct _TimMessageIqClass
{
  ThriftStructClass parent;
};
typedef struct _TimMessageIqClass TimMessageIqClass;

GType tim_message_iq_get_type (void);
#define TYPE_TIM_MESSAGE_IQ (tim_message_iq_get_type())
#define TIM_MESSAGE_IQ(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_MESSAGE_IQ, TimMessageIq))
#define TIM_MESSAGE_IQ_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_MESSAGE_IQ, TimMessageIqClass))
#define IS_TIM_MESSAGE_IQ(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_MESSAGE_IQ))
#define IS_TIM_MESSAGE_IQ_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_MESSAGE_IQ))
#define TIM_MESSAGE_IQ_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_MESSAGE_IQ, TimMessageIqClass))

/* struct TimAuth */
struct _TimAuth
{ 
  ThriftStruct parent; 

  /* public */
  gchar * domain;
  gboolean __isset_domain;
  gchar * username;
  gboolean __isset_username;
  gchar * pwd;
  gboolean __isset_pwd;
};
typedef struct _TimAuth TimAuth;

struct _TimAuthClass
{
  ThriftStructClass parent;
};
typedef struct _TimAuthClass TimAuthClass;

GType tim_auth_get_type (void);
#define TYPE_TIM_AUTH (tim_auth_get_type())
#define TIM_AUTH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_AUTH, TimAuth))
#define TIM_AUTH_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_AUTH, TimAuthClass))
#define IS_TIM_AUTH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_AUTH))
#define IS_TIM_AUTH_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_AUTH))
#define TIM_AUTH_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_AUTH, TimAuthClass))

/* struct TimMBeanList */
struct _TimMBeanList
{ 
  ThriftStruct parent; 

  /* public */
  gchar * threadId;
  GPtrArray * timMBeanList;
  gboolean __isset_timMBeanList;
  gchar * reqType;
  gboolean __isset_reqType;
  GHashTable * extraMap;
  gboolean __isset_extraMap;
};
typedef struct _TimMBeanList TimMBeanList;

struct _TimMBeanListClass
{
  ThriftStructClass parent;
};
typedef struct _TimMBeanListClass TimMBeanListClass;

GType tim_m_bean_list_get_type (void);
#define TYPE_TIM_M_BEAN_LIST (tim_m_bean_list_get_type())
#define TIM_M_BEAN_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_M_BEAN_LIST, TimMBeanList))
#define TIM_M_BEAN_LIST_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_M_BEAN_LIST, TimMBeanListClass))
#define IS_TIM_M_BEAN_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_M_BEAN_LIST))
#define IS_TIM_M_BEAN_LIST_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_M_BEAN_LIST))
#define TIM_M_BEAN_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_M_BEAN_LIST, TimMBeanListClass))

/* struct TimPBeanList */
struct _TimPBeanList
{ 
  ThriftStruct parent; 

  /* public */
  gchar * threadId;
  GPtrArray * timPBeanList;
  gboolean __isset_timPBeanList;
  gchar * reqType;
  gboolean __isset_reqType;
  GHashTable * extraMap;
  gboolean __isset_extraMap;
};
typedef struct _TimPBeanList TimPBeanList;

struct _TimPBeanListClass
{
  ThriftStructClass parent;
};
typedef struct _TimPBeanListClass TimPBeanListClass;

GType tim_p_bean_list_get_type (void);
#define TYPE_TIM_P_BEAN_LIST (tim_p_bean_list_get_type())
#define TIM_P_BEAN_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_P_BEAN_LIST, TimPBeanList))
#define TIM_P_BEAN_LIST_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_P_BEAN_LIST, TimPBeanListClass))
#define IS_TIM_P_BEAN_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_P_BEAN_LIST))
#define IS_TIM_P_BEAN_LIST_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_P_BEAN_LIST))
#define TIM_P_BEAN_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_P_BEAN_LIST, TimPBeanListClass))

/* struct TimPropertyBean */
struct _TimPropertyBean
{ 
  ThriftStruct parent; 

  /* public */
  gchar * threadId;
  gboolean __isset_threadId;
  gchar * interflow;
  gboolean __isset_interflow;
  gchar * tls;
  gboolean __isset_tls;
};
typedef struct _TimPropertyBean TimPropertyBean;

struct _TimPropertyBeanClass
{
  ThriftStructClass parent;
};
typedef struct _TimPropertyBeanClass TimPropertyBeanClass;

GType tim_property_bean_get_type (void);
#define TYPE_TIM_PROPERTY_BEAN (tim_property_bean_get_type())
#define TIM_PROPERTY_BEAN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIM_PROPERTY_BEAN, TimPropertyBean))
#define TIM_PROPERTY_BEAN_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_TIM_PROPERTY_BEAN, TimPropertyBeanClass))
#define IS_TIM_PROPERTY_BEAN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIM_PROPERTY_BEAN))
#define IS_TIM_PROPERTY_BEAN_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_TIM_PROPERTY_BEAN))
#define TIM_PROPERTY_BEAN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TIM_PROPERTY_BEAN, TimPropertyBeanClass))

/* constants */
#define PROTOCOLVERSION 4
#define PROTOCOLVERSIONNAME g_strdup ("1.1.0")
#define TIM_SC_SUCCESS g_strdup ("200")
#define TIM_SC_FAILED g_strdup ("400")

/* struct ITimTimStreamArgs */
struct _ITimTimStreamArgs
{ 
  ThriftStruct parent; 

  /* public */
  TimParam * param;
  gboolean __isset_param;
};
typedef struct _ITimTimStreamArgs ITimTimStreamArgs;

struct _ITimTimStreamArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimStreamArgsClass ITimTimStreamArgsClass;

GType i_tim_tim_stream_args_get_type (void);
#define TYPE_I_TIM_TIM_STREAM_ARGS (i_tim_tim_stream_args_get_type())
#define I_TIM_TIM_STREAM_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_STREAM_ARGS, ITimTimStreamArgs))
#define I_TIM_TIM_STREAM_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_STREAM_ARGS, ITimTimStreamArgsClass))
#define IS_I_TIM_TIM_STREAM_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_STREAM_ARGS))
#define IS_I_TIM_TIM_STREAM_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_STREAM_ARGS))
#define I_TIM_TIM_STREAM_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_STREAM_ARGS, ITimTimStreamArgsClass))

/* struct ITimTimStarttlsArgs */
struct _ITimTimStarttlsArgs
{ 
  ThriftStruct parent; 

  /* public */
};
typedef struct _ITimTimStarttlsArgs ITimTimStarttlsArgs;

struct _ITimTimStarttlsArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimStarttlsArgsClass ITimTimStarttlsArgsClass;

GType i_tim_tim_starttls_args_get_type (void);
#define TYPE_I_TIM_TIM_STARTTLS_ARGS (i_tim_tim_starttls_args_get_type())
#define I_TIM_TIM_STARTTLS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_STARTTLS_ARGS, ITimTimStarttlsArgs))
#define I_TIM_TIM_STARTTLS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_STARTTLS_ARGS, ITimTimStarttlsArgsClass))
#define IS_I_TIM_TIM_STARTTLS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_STARTTLS_ARGS))
#define IS_I_TIM_TIM_STARTTLS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_STARTTLS_ARGS))
#define I_TIM_TIM_STARTTLS_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_STARTTLS_ARGS, ITimTimStarttlsArgsClass))

/* struct ITimTimLoginArgs */
struct _ITimTimLoginArgs
{ 
  ThriftStruct parent; 

  /* public */
  Tid * tid;
  gboolean __isset_tid;
  gchar * pwd;
  gboolean __isset_pwd;
};
typedef struct _ITimTimLoginArgs ITimTimLoginArgs;

struct _ITimTimLoginArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimLoginArgsClass ITimTimLoginArgsClass;

GType i_tim_tim_login_args_get_type (void);
#define TYPE_I_TIM_TIM_LOGIN_ARGS (i_tim_tim_login_args_get_type())
#define I_TIM_TIM_LOGIN_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_LOGIN_ARGS, ITimTimLoginArgs))
#define I_TIM_TIM_LOGIN_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_LOGIN_ARGS, ITimTimLoginArgsClass))
#define IS_I_TIM_TIM_LOGIN_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_LOGIN_ARGS))
#define IS_I_TIM_TIM_LOGIN_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_LOGIN_ARGS))
#define I_TIM_TIM_LOGIN_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_LOGIN_ARGS, ITimTimLoginArgsClass))

/* struct ITimTimAckArgs */
struct _ITimTimAckArgs
{ 
  ThriftStruct parent; 

  /* public */
  TimAckBean * ab;
  gboolean __isset_ab;
};
typedef struct _ITimTimAckArgs ITimTimAckArgs;

struct _ITimTimAckArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimAckArgsClass ITimTimAckArgsClass;

GType i_tim_tim_ack_args_get_type (void);
#define TYPE_I_TIM_TIM_ACK_ARGS (i_tim_tim_ack_args_get_type())
#define I_TIM_TIM_ACK_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_ACK_ARGS, ITimTimAckArgs))
#define I_TIM_TIM_ACK_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_ACK_ARGS, ITimTimAckArgsClass))
#define IS_I_TIM_TIM_ACK_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_ACK_ARGS))
#define IS_I_TIM_TIM_ACK_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_ACK_ARGS))
#define I_TIM_TIM_ACK_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_ACK_ARGS, ITimTimAckArgsClass))

/* struct ITimTimPresenceArgs */
struct _ITimTimPresenceArgs
{ 
  ThriftStruct parent; 

  /* public */
  TimPBean * pbean;
  gboolean __isset_pbean;
};
typedef struct _ITimTimPresenceArgs ITimTimPresenceArgs;

struct _ITimTimPresenceArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimPresenceArgsClass ITimTimPresenceArgsClass;

GType i_tim_tim_presence_args_get_type (void);
#define TYPE_I_TIM_TIM_PRESENCE_ARGS (i_tim_tim_presence_args_get_type())
#define I_TIM_TIM_PRESENCE_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_PRESENCE_ARGS, ITimTimPresenceArgs))
#define I_TIM_TIM_PRESENCE_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_PRESENCE_ARGS, ITimTimPresenceArgsClass))
#define IS_I_TIM_TIM_PRESENCE_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_PRESENCE_ARGS))
#define IS_I_TIM_TIM_PRESENCE_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_PRESENCE_ARGS))
#define I_TIM_TIM_PRESENCE_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_PRESENCE_ARGS, ITimTimPresenceArgsClass))

/* struct ITimTimMessageArgs */
struct _ITimTimMessageArgs
{ 
  ThriftStruct parent; 

  /* public */
  TimMBean * mbean;
  gboolean __isset_mbean;
};
typedef struct _ITimTimMessageArgs ITimTimMessageArgs;

struct _ITimTimMessageArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimMessageArgsClass ITimTimMessageArgsClass;

GType i_tim_tim_message_args_get_type (void);
#define TYPE_I_TIM_TIM_MESSAGE_ARGS (i_tim_tim_message_args_get_type())
#define I_TIM_TIM_MESSAGE_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_MESSAGE_ARGS, ITimTimMessageArgs))
#define I_TIM_TIM_MESSAGE_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_MESSAGE_ARGS, ITimTimMessageArgsClass))
#define IS_I_TIM_TIM_MESSAGE_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_MESSAGE_ARGS))
#define IS_I_TIM_TIM_MESSAGE_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_MESSAGE_ARGS))
#define I_TIM_TIM_MESSAGE_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_MESSAGE_ARGS, ITimTimMessageArgsClass))

/* struct ITimTimPingArgs */
struct _ITimTimPingArgs
{ 
  ThriftStruct parent; 

  /* public */
  gchar * threadId;
  gboolean __isset_threadId;
};
typedef struct _ITimTimPingArgs ITimTimPingArgs;

struct _ITimTimPingArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimPingArgsClass ITimTimPingArgsClass;

GType i_tim_tim_ping_args_get_type (void);
#define TYPE_I_TIM_TIM_PING_ARGS (i_tim_tim_ping_args_get_type())
#define I_TIM_TIM_PING_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_PING_ARGS, ITimTimPingArgs))
#define I_TIM_TIM_PING_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_PING_ARGS, ITimTimPingArgsClass))
#define IS_I_TIM_TIM_PING_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_PING_ARGS))
#define IS_I_TIM_TIM_PING_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_PING_ARGS))
#define I_TIM_TIM_PING_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_PING_ARGS, ITimTimPingArgsClass))

/* struct ITimTimErrorArgs */
struct _ITimTimErrorArgs
{ 
  ThriftStruct parent; 

  /* public */
  TimError * e;
  gboolean __isset_e;
};
typedef struct _ITimTimErrorArgs ITimTimErrorArgs;

struct _ITimTimErrorArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimErrorArgsClass ITimTimErrorArgsClass;

GType i_tim_tim_error_args_get_type (void);
#define TYPE_I_TIM_TIM_ERROR_ARGS (i_tim_tim_error_args_get_type())
#define I_TIM_TIM_ERROR_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_ERROR_ARGS, ITimTimErrorArgs))
#define I_TIM_TIM_ERROR_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_ERROR_ARGS, ITimTimErrorArgsClass))
#define IS_I_TIM_TIM_ERROR_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_ERROR_ARGS))
#define IS_I_TIM_TIM_ERROR_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_ERROR_ARGS))
#define I_TIM_TIM_ERROR_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_ERROR_ARGS, ITimTimErrorArgsClass))

/* struct ITimTimLogoutArgs */
struct _ITimTimLogoutArgs
{ 
  ThriftStruct parent; 

  /* public */
};
typedef struct _ITimTimLogoutArgs ITimTimLogoutArgs;

struct _ITimTimLogoutArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimLogoutArgsClass ITimTimLogoutArgsClass;

GType i_tim_tim_logout_args_get_type (void);
#define TYPE_I_TIM_TIM_LOGOUT_ARGS (i_tim_tim_logout_args_get_type())
#define I_TIM_TIM_LOGOUT_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_LOGOUT_ARGS, ITimTimLogoutArgs))
#define I_TIM_TIM_LOGOUT_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_LOGOUT_ARGS, ITimTimLogoutArgsClass))
#define IS_I_TIM_TIM_LOGOUT_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_LOGOUT_ARGS))
#define IS_I_TIM_TIM_LOGOUT_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_LOGOUT_ARGS))
#define I_TIM_TIM_LOGOUT_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_LOGOUT_ARGS, ITimTimLogoutArgsClass))

/* struct ITimTimRegistArgs */
struct _ITimTimRegistArgs
{ 
  ThriftStruct parent; 

  /* public */
  Tid * tid;
  gboolean __isset_tid;
  gchar * auth;
  gboolean __isset_auth;
};
typedef struct _ITimTimRegistArgs ITimTimRegistArgs;

struct _ITimTimRegistArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimRegistArgsClass ITimTimRegistArgsClass;

GType i_tim_tim_regist_args_get_type (void);
#define TYPE_I_TIM_TIM_REGIST_ARGS (i_tim_tim_regist_args_get_type())
#define I_TIM_TIM_REGIST_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_REGIST_ARGS, ITimTimRegistArgs))
#define I_TIM_TIM_REGIST_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_REGIST_ARGS, ITimTimRegistArgsClass))
#define IS_I_TIM_TIM_REGIST_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_REGIST_ARGS))
#define IS_I_TIM_TIM_REGIST_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_REGIST_ARGS))
#define I_TIM_TIM_REGIST_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_REGIST_ARGS, ITimTimRegistArgsClass))

/* struct ITimTimRoserArgs */
struct _ITimTimRoserArgs
{ 
  ThriftStruct parent; 

  /* public */
  TimRoster * roster;
  gboolean __isset_roster;
};
typedef struct _ITimTimRoserArgs ITimTimRoserArgs;

struct _ITimTimRoserArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimRoserArgsClass ITimTimRoserArgsClass;

GType i_tim_tim_roser_args_get_type (void);
#define TYPE_I_TIM_TIM_ROSER_ARGS (i_tim_tim_roser_args_get_type())
#define I_TIM_TIM_ROSER_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_ROSER_ARGS, ITimTimRoserArgs))
#define I_TIM_TIM_ROSER_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_ROSER_ARGS, ITimTimRoserArgsClass))
#define IS_I_TIM_TIM_ROSER_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_ROSER_ARGS))
#define IS_I_TIM_TIM_ROSER_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_ROSER_ARGS))
#define I_TIM_TIM_ROSER_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_ROSER_ARGS, ITimTimRoserArgsClass))

/* struct ITimTimMessageListArgs */
struct _ITimTimMessageListArgs
{ 
  ThriftStruct parent; 

  /* public */
  TimMBeanList * mbeanList;
  gboolean __isset_mbeanList;
};
typedef struct _ITimTimMessageListArgs ITimTimMessageListArgs;

struct _ITimTimMessageListArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimMessageListArgsClass ITimTimMessageListArgsClass;

GType i_tim_tim_message_list_args_get_type (void);
#define TYPE_I_TIM_TIM_MESSAGE_LIST_ARGS (i_tim_tim_message_list_args_get_type())
#define I_TIM_TIM_MESSAGE_LIST_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_MESSAGE_LIST_ARGS, ITimTimMessageListArgs))
#define I_TIM_TIM_MESSAGE_LIST_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_MESSAGE_LIST_ARGS, ITimTimMessageListArgsClass))
#define IS_I_TIM_TIM_MESSAGE_LIST_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_MESSAGE_LIST_ARGS))
#define IS_I_TIM_TIM_MESSAGE_LIST_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_MESSAGE_LIST_ARGS))
#define I_TIM_TIM_MESSAGE_LIST_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_MESSAGE_LIST_ARGS, ITimTimMessageListArgsClass))

/* struct ITimTimPresenceListArgs */
struct _ITimTimPresenceListArgs
{ 
  ThriftStruct parent; 

  /* public */
  TimPBeanList * pbeanList;
  gboolean __isset_pbeanList;
};
typedef struct _ITimTimPresenceListArgs ITimTimPresenceListArgs;

struct _ITimTimPresenceListArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimPresenceListArgsClass ITimTimPresenceListArgsClass;

GType i_tim_tim_presence_list_args_get_type (void);
#define TYPE_I_TIM_TIM_PRESENCE_LIST_ARGS (i_tim_tim_presence_list_args_get_type())
#define I_TIM_TIM_PRESENCE_LIST_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_PRESENCE_LIST_ARGS, ITimTimPresenceListArgs))
#define I_TIM_TIM_PRESENCE_LIST_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_PRESENCE_LIST_ARGS, ITimTimPresenceListArgsClass))
#define IS_I_TIM_TIM_PRESENCE_LIST_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_PRESENCE_LIST_ARGS))
#define IS_I_TIM_TIM_PRESENCE_LIST_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_PRESENCE_LIST_ARGS))
#define I_TIM_TIM_PRESENCE_LIST_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_PRESENCE_LIST_ARGS, ITimTimPresenceListArgsClass))

/* struct ITimTimMessageIqArgs */
struct _ITimTimMessageIqArgs
{ 
  ThriftStruct parent; 

  /* public */
  TimMessageIq * timMsgIq;
  gboolean __isset_timMsgIq;
  gchar * iqType;
  gboolean __isset_iqType;
};
typedef struct _ITimTimMessageIqArgs ITimTimMessageIqArgs;

struct _ITimTimMessageIqArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimMessageIqArgsClass ITimTimMessageIqArgsClass;

GType i_tim_tim_message_iq_args_get_type (void);
#define TYPE_I_TIM_TIM_MESSAGE_IQ_ARGS (i_tim_tim_message_iq_args_get_type())
#define I_TIM_TIM_MESSAGE_IQ_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_MESSAGE_IQ_ARGS, ITimTimMessageIqArgs))
#define I_TIM_TIM_MESSAGE_IQ_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_MESSAGE_IQ_ARGS, ITimTimMessageIqArgsClass))
#define IS_I_TIM_TIM_MESSAGE_IQ_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_MESSAGE_IQ_ARGS))
#define IS_I_TIM_TIM_MESSAGE_IQ_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_MESSAGE_IQ_ARGS))
#define I_TIM_TIM_MESSAGE_IQ_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_MESSAGE_IQ_ARGS, ITimTimMessageIqArgsClass))

/* struct ITimTimMessageResultArgs */
struct _ITimTimMessageResultArgs
{ 
  ThriftStruct parent; 

  /* public */
  TimMBean * mbean;
  gboolean __isset_mbean;
};
typedef struct _ITimTimMessageResultArgs ITimTimMessageResultArgs;

struct _ITimTimMessageResultArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimMessageResultArgsClass ITimTimMessageResultArgsClass;

GType i_tim_tim_message_result_args_get_type (void);
#define TYPE_I_TIM_TIM_MESSAGE_RESULT_ARGS (i_tim_tim_message_result_args_get_type())
#define I_TIM_TIM_MESSAGE_RESULT_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_MESSAGE_RESULT_ARGS, ITimTimMessageResultArgs))
#define I_TIM_TIM_MESSAGE_RESULT_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_MESSAGE_RESULT_ARGS, ITimTimMessageResultArgsClass))
#define IS_I_TIM_TIM_MESSAGE_RESULT_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_MESSAGE_RESULT_ARGS))
#define IS_I_TIM_TIM_MESSAGE_RESULT_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_MESSAGE_RESULT_ARGS))
#define I_TIM_TIM_MESSAGE_RESULT_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_MESSAGE_RESULT_ARGS, ITimTimMessageResultArgsClass))

/* struct ITimTimPropertyArgs */
struct _ITimTimPropertyArgs
{ 
  ThriftStruct parent; 

  /* public */
  TimPropertyBean * tpb;
  gboolean __isset_tpb;
};
typedef struct _ITimTimPropertyArgs ITimTimPropertyArgs;

struct _ITimTimPropertyArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimPropertyArgsClass ITimTimPropertyArgsClass;

GType i_tim_tim_property_args_get_type (void);
#define TYPE_I_TIM_TIM_PROPERTY_ARGS (i_tim_tim_property_args_get_type())
#define I_TIM_TIM_PROPERTY_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_PROPERTY_ARGS, ITimTimPropertyArgs))
#define I_TIM_TIM_PROPERTY_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_PROPERTY_ARGS, ITimTimPropertyArgsClass))
#define IS_I_TIM_TIM_PROPERTY_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_PROPERTY_ARGS))
#define IS_I_TIM_TIM_PROPERTY_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_PROPERTY_ARGS))
#define I_TIM_TIM_PROPERTY_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_PROPERTY_ARGS, ITimTimPropertyArgsClass))

/* struct ITimTimRemoteUserAuthArgs */
struct _ITimTimRemoteUserAuthArgs
{ 
  ThriftStruct parent; 

  /* public */
  Tid * tid;
  gboolean __isset_tid;
  gchar * pwd;
  gboolean __isset_pwd;
  TimAuth * auth;
  gboolean __isset_auth;
};
typedef struct _ITimTimRemoteUserAuthArgs ITimTimRemoteUserAuthArgs;

struct _ITimTimRemoteUserAuthArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimRemoteUserAuthArgsClass ITimTimRemoteUserAuthArgsClass;

GType i_tim_tim_remote_user_auth_args_get_type (void);
#define TYPE_I_TIM_TIM_REMOTE_USER_AUTH_ARGS (i_tim_tim_remote_user_auth_args_get_type())
#define I_TIM_TIM_REMOTE_USER_AUTH_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_REMOTE_USER_AUTH_ARGS, ITimTimRemoteUserAuthArgs))
#define I_TIM_TIM_REMOTE_USER_AUTH_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_REMOTE_USER_AUTH_ARGS, ITimTimRemoteUserAuthArgsClass))
#define IS_I_TIM_TIM_REMOTE_USER_AUTH_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_REMOTE_USER_AUTH_ARGS))
#define IS_I_TIM_TIM_REMOTE_USER_AUTH_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_REMOTE_USER_AUTH_ARGS))
#define I_TIM_TIM_REMOTE_USER_AUTH_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_REMOTE_USER_AUTH_ARGS, ITimTimRemoteUserAuthArgsClass))

/* struct ITimTimRemoteUserAuthResult */
struct _ITimTimRemoteUserAuthResult
{ 
  ThriftStruct parent; 

  /* public */
  TimRemoteUserBean * success;
  gboolean __isset_success;
};
typedef struct _ITimTimRemoteUserAuthResult ITimTimRemoteUserAuthResult;

struct _ITimTimRemoteUserAuthResultClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimRemoteUserAuthResultClass ITimTimRemoteUserAuthResultClass;

GType i_tim_tim_remote_user_auth_result_get_type (void);
#define TYPE_I_TIM_TIM_REMOTE_USER_AUTH_RESULT (i_tim_tim_remote_user_auth_result_get_type())
#define I_TIM_TIM_REMOTE_USER_AUTH_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_REMOTE_USER_AUTH_RESULT, ITimTimRemoteUserAuthResult))
#define I_TIM_TIM_REMOTE_USER_AUTH_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_REMOTE_USER_AUTH_RESULT, ITimTimRemoteUserAuthResultClass))
#define IS_I_TIM_TIM_REMOTE_USER_AUTH_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_REMOTE_USER_AUTH_RESULT))
#define IS_I_TIM_TIM_REMOTE_USER_AUTH_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_REMOTE_USER_AUTH_RESULT))
#define I_TIM_TIM_REMOTE_USER_AUTH_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_REMOTE_USER_AUTH_RESULT, ITimTimRemoteUserAuthResultClass))

/* struct ITimTimRemoteUserGetArgs */
struct _ITimTimRemoteUserGetArgs
{ 
  ThriftStruct parent; 

  /* public */
  Tid * tid;
  gboolean __isset_tid;
  TimAuth * auth;
  gboolean __isset_auth;
};
typedef struct _ITimTimRemoteUserGetArgs ITimTimRemoteUserGetArgs;

struct _ITimTimRemoteUserGetArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimRemoteUserGetArgsClass ITimTimRemoteUserGetArgsClass;

GType i_tim_tim_remote_user_get_args_get_type (void);
#define TYPE_I_TIM_TIM_REMOTE_USER_GET_ARGS (i_tim_tim_remote_user_get_args_get_type())
#define I_TIM_TIM_REMOTE_USER_GET_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_REMOTE_USER_GET_ARGS, ITimTimRemoteUserGetArgs))
#define I_TIM_TIM_REMOTE_USER_GET_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_REMOTE_USER_GET_ARGS, ITimTimRemoteUserGetArgsClass))
#define IS_I_TIM_TIM_REMOTE_USER_GET_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_REMOTE_USER_GET_ARGS))
#define IS_I_TIM_TIM_REMOTE_USER_GET_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_REMOTE_USER_GET_ARGS))
#define I_TIM_TIM_REMOTE_USER_GET_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_REMOTE_USER_GET_ARGS, ITimTimRemoteUserGetArgsClass))

/* struct ITimTimRemoteUserGetResult */
struct _ITimTimRemoteUserGetResult
{ 
  ThriftStruct parent; 

  /* public */
  TimRemoteUserBean * success;
  gboolean __isset_success;
};
typedef struct _ITimTimRemoteUserGetResult ITimTimRemoteUserGetResult;

struct _ITimTimRemoteUserGetResultClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimRemoteUserGetResultClass ITimTimRemoteUserGetResultClass;

GType i_tim_tim_remote_user_get_result_get_type (void);
#define TYPE_I_TIM_TIM_REMOTE_USER_GET_RESULT (i_tim_tim_remote_user_get_result_get_type())
#define I_TIM_TIM_REMOTE_USER_GET_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_REMOTE_USER_GET_RESULT, ITimTimRemoteUserGetResult))
#define I_TIM_TIM_REMOTE_USER_GET_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_REMOTE_USER_GET_RESULT, ITimTimRemoteUserGetResultClass))
#define IS_I_TIM_TIM_REMOTE_USER_GET_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_REMOTE_USER_GET_RESULT))
#define IS_I_TIM_TIM_REMOTE_USER_GET_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_REMOTE_USER_GET_RESULT))
#define I_TIM_TIM_REMOTE_USER_GET_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_REMOTE_USER_GET_RESULT, ITimTimRemoteUserGetResultClass))

/* struct ITimTimRemoteUserEditArgs */
struct _ITimTimRemoteUserEditArgs
{ 
  ThriftStruct parent; 

  /* public */
  Tid * tid;
  gboolean __isset_tid;
  TimUserBean * ub;
  gboolean __isset_ub;
  TimAuth * auth;
  gboolean __isset_auth;
};
typedef struct _ITimTimRemoteUserEditArgs ITimTimRemoteUserEditArgs;

struct _ITimTimRemoteUserEditArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimRemoteUserEditArgsClass ITimTimRemoteUserEditArgsClass;

GType i_tim_tim_remote_user_edit_args_get_type (void);
#define TYPE_I_TIM_TIM_REMOTE_USER_EDIT_ARGS (i_tim_tim_remote_user_edit_args_get_type())
#define I_TIM_TIM_REMOTE_USER_EDIT_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_REMOTE_USER_EDIT_ARGS, ITimTimRemoteUserEditArgs))
#define I_TIM_TIM_REMOTE_USER_EDIT_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_REMOTE_USER_EDIT_ARGS, ITimTimRemoteUserEditArgsClass))
#define IS_I_TIM_TIM_REMOTE_USER_EDIT_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_REMOTE_USER_EDIT_ARGS))
#define IS_I_TIM_TIM_REMOTE_USER_EDIT_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_REMOTE_USER_EDIT_ARGS))
#define I_TIM_TIM_REMOTE_USER_EDIT_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_REMOTE_USER_EDIT_ARGS, ITimTimRemoteUserEditArgsClass))

/* struct ITimTimRemoteUserEditResult */
struct _ITimTimRemoteUserEditResult
{ 
  ThriftStruct parent; 

  /* public */
  TimRemoteUserBean * success;
  gboolean __isset_success;
};
typedef struct _ITimTimRemoteUserEditResult ITimTimRemoteUserEditResult;

struct _ITimTimRemoteUserEditResultClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimRemoteUserEditResultClass ITimTimRemoteUserEditResultClass;

GType i_tim_tim_remote_user_edit_result_get_type (void);
#define TYPE_I_TIM_TIM_REMOTE_USER_EDIT_RESULT (i_tim_tim_remote_user_edit_result_get_type())
#define I_TIM_TIM_REMOTE_USER_EDIT_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_REMOTE_USER_EDIT_RESULT, ITimTimRemoteUserEditResult))
#define I_TIM_TIM_REMOTE_USER_EDIT_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_REMOTE_USER_EDIT_RESULT, ITimTimRemoteUserEditResultClass))
#define IS_I_TIM_TIM_REMOTE_USER_EDIT_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_REMOTE_USER_EDIT_RESULT))
#define IS_I_TIM_TIM_REMOTE_USER_EDIT_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_REMOTE_USER_EDIT_RESULT))
#define I_TIM_TIM_REMOTE_USER_EDIT_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_REMOTE_USER_EDIT_RESULT, ITimTimRemoteUserEditResultClass))

/* struct ITimTimResponsePresenceArgs */
struct _ITimTimResponsePresenceArgs
{ 
  ThriftStruct parent; 

  /* public */
  TimPBean * pbean;
  gboolean __isset_pbean;
  TimAuth * auth;
  gboolean __isset_auth;
};
typedef struct _ITimTimResponsePresenceArgs ITimTimResponsePresenceArgs;

struct _ITimTimResponsePresenceArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimResponsePresenceArgsClass ITimTimResponsePresenceArgsClass;

GType i_tim_tim_response_presence_args_get_type (void);
#define TYPE_I_TIM_TIM_RESPONSE_PRESENCE_ARGS (i_tim_tim_response_presence_args_get_type())
#define I_TIM_TIM_RESPONSE_PRESENCE_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_RESPONSE_PRESENCE_ARGS, ITimTimResponsePresenceArgs))
#define I_TIM_TIM_RESPONSE_PRESENCE_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_RESPONSE_PRESENCE_ARGS, ITimTimResponsePresenceArgsClass))
#define IS_I_TIM_TIM_RESPONSE_PRESENCE_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_RESPONSE_PRESENCE_ARGS))
#define IS_I_TIM_TIM_RESPONSE_PRESENCE_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_RESPONSE_PRESENCE_ARGS))
#define I_TIM_TIM_RESPONSE_PRESENCE_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_RESPONSE_PRESENCE_ARGS, ITimTimResponsePresenceArgsClass))

/* struct ITimTimResponsePresenceResult */
struct _ITimTimResponsePresenceResult
{ 
  ThriftStruct parent; 

  /* public */
  TimResponseBean * success;
  gboolean __isset_success;
};
typedef struct _ITimTimResponsePresenceResult ITimTimResponsePresenceResult;

struct _ITimTimResponsePresenceResultClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimResponsePresenceResultClass ITimTimResponsePresenceResultClass;

GType i_tim_tim_response_presence_result_get_type (void);
#define TYPE_I_TIM_TIM_RESPONSE_PRESENCE_RESULT (i_tim_tim_response_presence_result_get_type())
#define I_TIM_TIM_RESPONSE_PRESENCE_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_RESPONSE_PRESENCE_RESULT, ITimTimResponsePresenceResult))
#define I_TIM_TIM_RESPONSE_PRESENCE_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_RESPONSE_PRESENCE_RESULT, ITimTimResponsePresenceResultClass))
#define IS_I_TIM_TIM_RESPONSE_PRESENCE_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_RESPONSE_PRESENCE_RESULT))
#define IS_I_TIM_TIM_RESPONSE_PRESENCE_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_RESPONSE_PRESENCE_RESULT))
#define I_TIM_TIM_RESPONSE_PRESENCE_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_RESPONSE_PRESENCE_RESULT, ITimTimResponsePresenceResultClass))

/* struct ITimTimResponseMessageArgs */
struct _ITimTimResponseMessageArgs
{ 
  ThriftStruct parent; 

  /* public */
  TimMBean * mbean;
  gboolean __isset_mbean;
  TimAuth * auth;
  gboolean __isset_auth;
};
typedef struct _ITimTimResponseMessageArgs ITimTimResponseMessageArgs;

struct _ITimTimResponseMessageArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimResponseMessageArgsClass ITimTimResponseMessageArgsClass;

GType i_tim_tim_response_message_args_get_type (void);
#define TYPE_I_TIM_TIM_RESPONSE_MESSAGE_ARGS (i_tim_tim_response_message_args_get_type())
#define I_TIM_TIM_RESPONSE_MESSAGE_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_ARGS, ITimTimResponseMessageArgs))
#define I_TIM_TIM_RESPONSE_MESSAGE_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_RESPONSE_MESSAGE_ARGS, ITimTimResponseMessageArgsClass))
#define IS_I_TIM_TIM_RESPONSE_MESSAGE_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_ARGS))
#define IS_I_TIM_TIM_RESPONSE_MESSAGE_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_ARGS))
#define I_TIM_TIM_RESPONSE_MESSAGE_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_ARGS, ITimTimResponseMessageArgsClass))

/* struct ITimTimResponseMessageResult */
struct _ITimTimResponseMessageResult
{ 
  ThriftStruct parent; 

  /* public */
  TimResponseBean * success;
  gboolean __isset_success;
};
typedef struct _ITimTimResponseMessageResult ITimTimResponseMessageResult;

struct _ITimTimResponseMessageResultClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimResponseMessageResultClass ITimTimResponseMessageResultClass;

GType i_tim_tim_response_message_result_get_type (void);
#define TYPE_I_TIM_TIM_RESPONSE_MESSAGE_RESULT (i_tim_tim_response_message_result_get_type())
#define I_TIM_TIM_RESPONSE_MESSAGE_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_RESULT, ITimTimResponseMessageResult))
#define I_TIM_TIM_RESPONSE_MESSAGE_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_RESPONSE_MESSAGE_RESULT, ITimTimResponseMessageResultClass))
#define IS_I_TIM_TIM_RESPONSE_MESSAGE_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_RESULT))
#define IS_I_TIM_TIM_RESPONSE_MESSAGE_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_RESULT))
#define I_TIM_TIM_RESPONSE_MESSAGE_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_RESULT, ITimTimResponseMessageResultClass))

/* struct ITimTimResponseMessageIqArgs */
struct _ITimTimResponseMessageIqArgs
{ 
  ThriftStruct parent; 

  /* public */
  TimMessageIq * timMsgIq;
  gboolean __isset_timMsgIq;
  gchar * iqType;
  gboolean __isset_iqType;
  TimAuth * auth;
  gboolean __isset_auth;
};
typedef struct _ITimTimResponseMessageIqArgs ITimTimResponseMessageIqArgs;

struct _ITimTimResponseMessageIqArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimResponseMessageIqArgsClass ITimTimResponseMessageIqArgsClass;

GType i_tim_tim_response_message_iq_args_get_type (void);
#define TYPE_I_TIM_TIM_RESPONSE_MESSAGE_IQ_ARGS (i_tim_tim_response_message_iq_args_get_type())
#define I_TIM_TIM_RESPONSE_MESSAGE_IQ_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_IQ_ARGS, ITimTimResponseMessageIqArgs))
#define I_TIM_TIM_RESPONSE_MESSAGE_IQ_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_RESPONSE_MESSAGE_IQ_ARGS, ITimTimResponseMessageIqArgsClass))
#define IS_I_TIM_TIM_RESPONSE_MESSAGE_IQ_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_IQ_ARGS))
#define IS_I_TIM_TIM_RESPONSE_MESSAGE_IQ_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_IQ_ARGS))
#define I_TIM_TIM_RESPONSE_MESSAGE_IQ_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_IQ_ARGS, ITimTimResponseMessageIqArgsClass))

/* struct ITimTimResponseMessageIqResult */
struct _ITimTimResponseMessageIqResult
{ 
  ThriftStruct parent; 

  /* public */
  TimMBeanList * success;
  gboolean __isset_success;
};
typedef struct _ITimTimResponseMessageIqResult ITimTimResponseMessageIqResult;

struct _ITimTimResponseMessageIqResultClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimResponseMessageIqResultClass ITimTimResponseMessageIqResultClass;

GType i_tim_tim_response_message_iq_result_get_type (void);
#define TYPE_I_TIM_TIM_RESPONSE_MESSAGE_IQ_RESULT (i_tim_tim_response_message_iq_result_get_type())
#define I_TIM_TIM_RESPONSE_MESSAGE_IQ_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_IQ_RESULT, ITimTimResponseMessageIqResult))
#define I_TIM_TIM_RESPONSE_MESSAGE_IQ_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_RESPONSE_MESSAGE_IQ_RESULT, ITimTimResponseMessageIqResultClass))
#define IS_I_TIM_TIM_RESPONSE_MESSAGE_IQ_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_IQ_RESULT))
#define IS_I_TIM_TIM_RESPONSE_MESSAGE_IQ_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_IQ_RESULT))
#define I_TIM_TIM_RESPONSE_MESSAGE_IQ_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_IQ_RESULT, ITimTimResponseMessageIqResultClass))

/* struct ITimTimResponsePresenceListArgs */
struct _ITimTimResponsePresenceListArgs
{ 
  ThriftStruct parent; 

  /* public */
  TimPBeanList * pbeanList;
  gboolean __isset_pbeanList;
  TimAuth * auth;
  gboolean __isset_auth;
};
typedef struct _ITimTimResponsePresenceListArgs ITimTimResponsePresenceListArgs;

struct _ITimTimResponsePresenceListArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimResponsePresenceListArgsClass ITimTimResponsePresenceListArgsClass;

GType i_tim_tim_response_presence_list_args_get_type (void);
#define TYPE_I_TIM_TIM_RESPONSE_PRESENCE_LIST_ARGS (i_tim_tim_response_presence_list_args_get_type())
#define I_TIM_TIM_RESPONSE_PRESENCE_LIST_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_RESPONSE_PRESENCE_LIST_ARGS, ITimTimResponsePresenceListArgs))
#define I_TIM_TIM_RESPONSE_PRESENCE_LIST_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_RESPONSE_PRESENCE_LIST_ARGS, ITimTimResponsePresenceListArgsClass))
#define IS_I_TIM_TIM_RESPONSE_PRESENCE_LIST_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_RESPONSE_PRESENCE_LIST_ARGS))
#define IS_I_TIM_TIM_RESPONSE_PRESENCE_LIST_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_RESPONSE_PRESENCE_LIST_ARGS))
#define I_TIM_TIM_RESPONSE_PRESENCE_LIST_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_RESPONSE_PRESENCE_LIST_ARGS, ITimTimResponsePresenceListArgsClass))

/* struct ITimTimResponsePresenceListResult */
struct _ITimTimResponsePresenceListResult
{ 
  ThriftStruct parent; 

  /* public */
  TimResponseBean * success;
  gboolean __isset_success;
};
typedef struct _ITimTimResponsePresenceListResult ITimTimResponsePresenceListResult;

struct _ITimTimResponsePresenceListResultClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimResponsePresenceListResultClass ITimTimResponsePresenceListResultClass;

GType i_tim_tim_response_presence_list_result_get_type (void);
#define TYPE_I_TIM_TIM_RESPONSE_PRESENCE_LIST_RESULT (i_tim_tim_response_presence_list_result_get_type())
#define I_TIM_TIM_RESPONSE_PRESENCE_LIST_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_RESPONSE_PRESENCE_LIST_RESULT, ITimTimResponsePresenceListResult))
#define I_TIM_TIM_RESPONSE_PRESENCE_LIST_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_RESPONSE_PRESENCE_LIST_RESULT, ITimTimResponsePresenceListResultClass))
#define IS_I_TIM_TIM_RESPONSE_PRESENCE_LIST_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_RESPONSE_PRESENCE_LIST_RESULT))
#define IS_I_TIM_TIM_RESPONSE_PRESENCE_LIST_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_RESPONSE_PRESENCE_LIST_RESULT))
#define I_TIM_TIM_RESPONSE_PRESENCE_LIST_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_RESPONSE_PRESENCE_LIST_RESULT, ITimTimResponsePresenceListResultClass))

/* struct ITimTimResponseMessageListArgs */
struct _ITimTimResponseMessageListArgs
{ 
  ThriftStruct parent; 

  /* public */
  TimMBeanList * mbeanList;
  gboolean __isset_mbeanList;
  TimAuth * auth;
  gboolean __isset_auth;
};
typedef struct _ITimTimResponseMessageListArgs ITimTimResponseMessageListArgs;

struct _ITimTimResponseMessageListArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimResponseMessageListArgsClass ITimTimResponseMessageListArgsClass;

GType i_tim_tim_response_message_list_args_get_type (void);
#define TYPE_I_TIM_TIM_RESPONSE_MESSAGE_LIST_ARGS (i_tim_tim_response_message_list_args_get_type())
#define I_TIM_TIM_RESPONSE_MESSAGE_LIST_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_LIST_ARGS, ITimTimResponseMessageListArgs))
#define I_TIM_TIM_RESPONSE_MESSAGE_LIST_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_RESPONSE_MESSAGE_LIST_ARGS, ITimTimResponseMessageListArgsClass))
#define IS_I_TIM_TIM_RESPONSE_MESSAGE_LIST_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_LIST_ARGS))
#define IS_I_TIM_TIM_RESPONSE_MESSAGE_LIST_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_LIST_ARGS))
#define I_TIM_TIM_RESPONSE_MESSAGE_LIST_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_LIST_ARGS, ITimTimResponseMessageListArgsClass))

/* struct ITimTimResponseMessageListResult */
struct _ITimTimResponseMessageListResult
{ 
  ThriftStruct parent; 

  /* public */
  TimResponseBean * success;
  gboolean __isset_success;
};
typedef struct _ITimTimResponseMessageListResult ITimTimResponseMessageListResult;

struct _ITimTimResponseMessageListResultClass
{
  ThriftStructClass parent;
};
typedef struct _ITimTimResponseMessageListResultClass ITimTimResponseMessageListResultClass;

GType i_tim_tim_response_message_list_result_get_type (void);
#define TYPE_I_TIM_TIM_RESPONSE_MESSAGE_LIST_RESULT (i_tim_tim_response_message_list_result_get_type())
#define I_TIM_TIM_RESPONSE_MESSAGE_LIST_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_LIST_RESULT, ITimTimResponseMessageListResult))
#define I_TIM_TIM_RESPONSE_MESSAGE_LIST_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_I_TIM_TIM_RESPONSE_MESSAGE_LIST_RESULT, ITimTimResponseMessageListResultClass))
#define IS_I_TIM_TIM_RESPONSE_MESSAGE_LIST_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_LIST_RESULT))
#define IS_I_TIM_TIM_RESPONSE_MESSAGE_LIST_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_LIST_RESULT))
#define I_TIM_TIM_RESPONSE_MESSAGE_LIST_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_I_TIM_TIM_RESPONSE_MESSAGE_LIST_RESULT, ITimTimResponseMessageListResultClass))

#endif /* TIM_TYPES_H */
