/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tim_TYPES_H
#define tim_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>




class TimError;

class TimNode;

class TimAckBean;

class TimHBean;

class TimParam;

class TimTime;

class TimArea;

class Tid;

class TimUserBean;

class TimRoom;

class TimPBean;

class TimMBean;

class TimIqBean;

class TimRoster;

class TimRemoteUserBean;

class TimRemoteRoom;

class TimResponseBean;

class TimSock5Bean;

class TimSock5Bytes;

class TimPage;

class TimMessageIq;

class TimAuth;

class TimMBeanList;

class TimPBeanList;

class TimPropertyBean;

typedef struct _TimError__isset {
  _TimError__isset() : errCode(false), errMsg(false) {}
  bool errCode :1;
  bool errMsg :1;
} _TimError__isset;

class TimError {
 public:

  TimError(const TimError&);
  TimError& operator=(const TimError&);
  TimError() : errCode(0), errMsg() {
  }

  virtual ~TimError() throw();
  int32_t errCode;
  std::string errMsg;

  _TimError__isset __isset;

  void __set_errCode(const int32_t val);

  void __set_errMsg(const std::string& val);

  bool operator == (const TimError & rhs) const
  {
    if (__isset.errCode != rhs.__isset.errCode)
      return false;
    else if (__isset.errCode && !(errCode == rhs.errCode))
      return false;
    if (__isset.errMsg != rhs.__isset.errMsg)
      return false;
    else if (__isset.errMsg && !(errMsg == rhs.errMsg))
      return false;
    return true;
  }
  bool operator != (const TimError &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimError & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimError &a, TimError &b);

inline std::ostream& operator<<(std::ostream& out, const TimError& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimNode__isset {
  _TimNode__isset() : key(false), value(false) {}
  bool key :1;
  bool value :1;
} _TimNode__isset;

class TimNode {
 public:

  TimNode(const TimNode&);
  TimNode& operator=(const TimNode&);
  TimNode() : key(), value() {
  }

  virtual ~TimNode() throw();
  std::string key;
  std::string value;

  _TimNode__isset __isset;

  void __set_key(const std::string& val);

  void __set_value(const std::string& val);

  bool operator == (const TimNode & rhs) const
  {
    if (__isset.key != rhs.__isset.key)
      return false;
    else if (__isset.key && !(key == rhs.key))
      return false;
    if (__isset.value != rhs.__isset.value)
      return false;
    else if (__isset.value && !(value == rhs.value))
      return false;
    return true;
  }
  bool operator != (const TimNode &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimNode & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimNode &a, TimNode &b);

inline std::ostream& operator<<(std::ostream& out, const TimNode& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimAckBean__isset {
  _TimAckBean__isset() : id(false), ackType(false), ackStatus(false), extraList(false), err(false), extraMap(false) {}
  bool id :1;
  bool ackType :1;
  bool ackStatus :1;
  bool extraList :1;
  bool err :1;
  bool extraMap :1;
} _TimAckBean__isset;

class TimAckBean {
 public:

  TimAckBean(const TimAckBean&);
  TimAckBean& operator=(const TimAckBean&);
  TimAckBean() : id(), ackType(), ackStatus() {
  }

  virtual ~TimAckBean() throw();
  std::string id;
  std::string ackType;
  std::string ackStatus;
  std::vector<TimNode>  extraList;
  TimError err;
  std::map<std::string, std::string>  extraMap;

  _TimAckBean__isset __isset;

  void __set_id(const std::string& val);

  void __set_ackType(const std::string& val);

  void __set_ackStatus(const std::string& val);

  void __set_extraList(const std::vector<TimNode> & val);

  void __set_err(const TimError& val);

  void __set_extraMap(const std::map<std::string, std::string> & val);

  bool operator == (const TimAckBean & rhs) const
  {
    if (__isset.id != rhs.__isset.id)
      return false;
    else if (__isset.id && !(id == rhs.id))
      return false;
    if (__isset.ackType != rhs.__isset.ackType)
      return false;
    else if (__isset.ackType && !(ackType == rhs.ackType))
      return false;
    if (__isset.ackStatus != rhs.__isset.ackStatus)
      return false;
    else if (__isset.ackStatus && !(ackStatus == rhs.ackStatus))
      return false;
    if (__isset.extraList != rhs.__isset.extraList)
      return false;
    else if (__isset.extraList && !(extraList == rhs.extraList))
      return false;
    if (__isset.err != rhs.__isset.err)
      return false;
    else if (__isset.err && !(err == rhs.err))
      return false;
    if (__isset.extraMap != rhs.__isset.extraMap)
      return false;
    else if (__isset.extraMap && !(extraMap == rhs.extraMap))
      return false;
    return true;
  }
  bool operator != (const TimAckBean &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimAckBean & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimAckBean &a, TimAckBean &b);

inline std::ostream& operator<<(std::ostream& out, const TimAckBean& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimHBean__isset {
  _TimHBean__isset() : platform(false) {}
  bool platform :1;
} _TimHBean__isset;

class TimHBean {
 public:

  TimHBean(const TimHBean&);
  TimHBean& operator=(const TimHBean&);
  TimHBean() : chl(0), platform(0), version(0) {
  }

  virtual ~TimHBean() throw();
  int32_t chl;
  int32_t platform;
  int16_t version;

  _TimHBean__isset __isset;

  void __set_chl(const int32_t val);

  void __set_platform(const int32_t val);

  void __set_version(const int16_t val);

  bool operator == (const TimHBean & rhs) const
  {
    if (!(chl == rhs.chl))
      return false;
    if (__isset.platform != rhs.__isset.platform)
      return false;
    else if (__isset.platform && !(platform == rhs.platform))
      return false;
    if (!(version == rhs.version))
      return false;
    return true;
  }
  bool operator != (const TimHBean &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimHBean & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimHBean &a, TimHBean &b);

inline std::ostream& operator<<(std::ostream& out, const TimHBean& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimParam__isset {
  _TimParam__isset() : timestamp(false), version(false), lang(false), extraList(false), extraMap(false), interflow(false), tls(false) {}
  bool timestamp :1;
  bool version :1;
  bool lang :1;
  bool extraList :1;
  bool extraMap :1;
  bool interflow :1;
  bool tls :1;
} _TimParam__isset;

class TimParam {
 public:

  TimParam(const TimParam&);
  TimParam& operator=(const TimParam&);
  TimParam() : timestamp(), version(0), lang(), interflow(), tls() {
  }

  virtual ~TimParam() throw();
  std::string timestamp;
  int16_t version;
  std::string lang;
  std::vector<TimNode>  extraList;
  std::map<std::string, std::string>  extraMap;
  std::string interflow;
  std::string tls;

  _TimParam__isset __isset;

  void __set_timestamp(const std::string& val);

  void __set_version(const int16_t val);

  void __set_lang(const std::string& val);

  void __set_extraList(const std::vector<TimNode> & val);

  void __set_extraMap(const std::map<std::string, std::string> & val);

  void __set_interflow(const std::string& val);

  void __set_tls(const std::string& val);

  bool operator == (const TimParam & rhs) const
  {
    if (__isset.timestamp != rhs.__isset.timestamp)
      return false;
    else if (__isset.timestamp && !(timestamp == rhs.timestamp))
      return false;
    if (__isset.version != rhs.__isset.version)
      return false;
    else if (__isset.version && !(version == rhs.version))
      return false;
    if (__isset.lang != rhs.__isset.lang)
      return false;
    else if (__isset.lang && !(lang == rhs.lang))
      return false;
    if (__isset.extraList != rhs.__isset.extraList)
      return false;
    else if (__isset.extraList && !(extraList == rhs.extraList))
      return false;
    if (__isset.extraMap != rhs.__isset.extraMap)
      return false;
    else if (__isset.extraMap && !(extraMap == rhs.extraMap))
      return false;
    if (__isset.interflow != rhs.__isset.interflow)
      return false;
    else if (__isset.interflow && !(interflow == rhs.interflow))
      return false;
    if (__isset.tls != rhs.__isset.tls)
      return false;
    else if (__isset.tls && !(tls == rhs.tls))
      return false;
    return true;
  }
  bool operator != (const TimParam &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimParam & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimParam &a, TimParam &b);

inline std::ostream& operator<<(std::ostream& out, const TimParam& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimTime__isset {
  _TimTime__isset() : timestamp(false), formattime(false) {}
  bool timestamp :1;
  bool formattime :1;
} _TimTime__isset;

class TimTime {
 public:

  TimTime(const TimTime&);
  TimTime& operator=(const TimTime&);
  TimTime() : timestamp(), formattime() {
  }

  virtual ~TimTime() throw();
  std::string timestamp;
  std::string formattime;

  _TimTime__isset __isset;

  void __set_timestamp(const std::string& val);

  void __set_formattime(const std::string& val);

  bool operator == (const TimTime & rhs) const
  {
    if (__isset.timestamp != rhs.__isset.timestamp)
      return false;
    else if (__isset.timestamp && !(timestamp == rhs.timestamp))
      return false;
    if (__isset.formattime != rhs.__isset.formattime)
      return false;
    else if (__isset.formattime && !(formattime == rhs.formattime))
      return false;
    return true;
  }
  bool operator != (const TimTime &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimTime & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimTime &a, TimTime &b);

inline std::ostream& operator<<(std::ostream& out, const TimTime& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimArea__isset {
  _TimArea__isset() : country(false), province(false), city(false), extraList(false), extraMap(false) {}
  bool country :1;
  bool province :1;
  bool city :1;
  bool extraList :1;
  bool extraMap :1;
} _TimArea__isset;

class TimArea {
 public:

  TimArea(const TimArea&);
  TimArea& operator=(const TimArea&);
  TimArea() : country(), province(), city() {
  }

  virtual ~TimArea() throw();
  std::string country;
  std::string province;
  std::string city;
  std::vector<TimNode>  extraList;
  std::map<std::string, std::string>  extraMap;

  _TimArea__isset __isset;

  void __set_country(const std::string& val);

  void __set_province(const std::string& val);

  void __set_city(const std::string& val);

  void __set_extraList(const std::vector<TimNode> & val);

  void __set_extraMap(const std::map<std::string, std::string> & val);

  bool operator == (const TimArea & rhs) const
  {
    if (__isset.country != rhs.__isset.country)
      return false;
    else if (__isset.country && !(country == rhs.country))
      return false;
    if (__isset.province != rhs.__isset.province)
      return false;
    else if (__isset.province && !(province == rhs.province))
      return false;
    if (__isset.city != rhs.__isset.city)
      return false;
    else if (__isset.city && !(city == rhs.city))
      return false;
    if (__isset.extraList != rhs.__isset.extraList)
      return false;
    else if (__isset.extraList && !(extraList == rhs.extraList))
      return false;
    if (__isset.extraMap != rhs.__isset.extraMap)
      return false;
    else if (__isset.extraMap && !(extraMap == rhs.extraMap))
      return false;
    return true;
  }
  bool operator != (const TimArea &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimArea & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimArea &a, TimArea &b);

inline std::ostream& operator<<(std::ostream& out, const TimArea& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _Tid__isset {
  _Tid__isset() : domain(false), resource(false), type(false), extraList(false), extraMap(false) {}
  bool domain :1;
  bool resource :1;
  bool type :1;
  bool extraList :1;
  bool extraMap :1;
} _Tid__isset;

class Tid {
 public:

  Tid(const Tid&);
  Tid& operator=(const Tid&);
  Tid() : name(), domain(), resource(), type() {
  }

  virtual ~Tid() throw();
  std::string name;
  std::string domain;
  std::string resource;
  std::string type;
  std::vector<TimNode>  extraList;
  std::map<std::string, std::string>  extraMap;

  _Tid__isset __isset;

  void __set_name(const std::string& val);

  void __set_domain(const std::string& val);

  void __set_resource(const std::string& val);

  void __set_type(const std::string& val);

  void __set_extraList(const std::vector<TimNode> & val);

  void __set_extraMap(const std::map<std::string, std::string> & val);

  bool operator == (const Tid & rhs) const
  {
    if (!(name == rhs.name))
      return false;
    if (__isset.domain != rhs.__isset.domain)
      return false;
    else if (__isset.domain && !(domain == rhs.domain))
      return false;
    if (__isset.resource != rhs.__isset.resource)
      return false;
    else if (__isset.resource && !(resource == rhs.resource))
      return false;
    if (__isset.type != rhs.__isset.type)
      return false;
    else if (__isset.type && !(type == rhs.type))
      return false;
    if (__isset.extraList != rhs.__isset.extraList)
      return false;
    else if (__isset.extraList && !(extraList == rhs.extraList))
      return false;
    if (__isset.extraMap != rhs.__isset.extraMap)
      return false;
    else if (__isset.extraMap && !(extraMap == rhs.extraMap))
      return false;
    return true;
  }
  bool operator != (const Tid &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Tid & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(Tid &a, Tid &b);

inline std::ostream& operator<<(std::ostream& out, const Tid& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimUserBean__isset {
  _TimUserBean__isset() : tid(false), nickname(false), remarkname(false), brithday(false), gender(false), headurl(false), area(false), headbyte(false), photoBytes(false), extraList(false), extraMap(false) {}
  bool tid :1;
  bool nickname :1;
  bool remarkname :1;
  bool brithday :1;
  bool gender :1;
  bool headurl :1;
  bool area :1;
  bool headbyte :1;
  bool photoBytes :1;
  bool extraList :1;
  bool extraMap :1;
} _TimUserBean__isset;

class TimUserBean {
 public:

  TimUserBean(const TimUserBean&);
  TimUserBean& operator=(const TimUserBean&);
  TimUserBean() : nickname(), remarkname(), brithday(), gender(0), headurl(), headbyte() {
  }

  virtual ~TimUserBean() throw();
  Tid tid;
  std::string nickname;
  std::string remarkname;
  std::string brithday;
  int16_t gender;
  std::string headurl;
  TimArea area;
  std::string headbyte;
  std::vector<std::string>  photoBytes;
  std::vector<TimNode>  extraList;
  std::map<std::string, std::string>  extraMap;

  _TimUserBean__isset __isset;

  void __set_tid(const Tid& val);

  void __set_nickname(const std::string& val);

  void __set_remarkname(const std::string& val);

  void __set_brithday(const std::string& val);

  void __set_gender(const int16_t val);

  void __set_headurl(const std::string& val);

  void __set_area(const TimArea& val);

  void __set_headbyte(const std::string& val);

  void __set_photoBytes(const std::vector<std::string> & val);

  void __set_extraList(const std::vector<TimNode> & val);

  void __set_extraMap(const std::map<std::string, std::string> & val);

  bool operator == (const TimUserBean & rhs) const
  {
    if (__isset.tid != rhs.__isset.tid)
      return false;
    else if (__isset.tid && !(tid == rhs.tid))
      return false;
    if (__isset.nickname != rhs.__isset.nickname)
      return false;
    else if (__isset.nickname && !(nickname == rhs.nickname))
      return false;
    if (__isset.remarkname != rhs.__isset.remarkname)
      return false;
    else if (__isset.remarkname && !(remarkname == rhs.remarkname))
      return false;
    if (__isset.brithday != rhs.__isset.brithday)
      return false;
    else if (__isset.brithday && !(brithday == rhs.brithday))
      return false;
    if (__isset.gender != rhs.__isset.gender)
      return false;
    else if (__isset.gender && !(gender == rhs.gender))
      return false;
    if (__isset.headurl != rhs.__isset.headurl)
      return false;
    else if (__isset.headurl && !(headurl == rhs.headurl))
      return false;
    if (__isset.area != rhs.__isset.area)
      return false;
    else if (__isset.area && !(area == rhs.area))
      return false;
    if (__isset.headbyte != rhs.__isset.headbyte)
      return false;
    else if (__isset.headbyte && !(headbyte == rhs.headbyte))
      return false;
    if (__isset.photoBytes != rhs.__isset.photoBytes)
      return false;
    else if (__isset.photoBytes && !(photoBytes == rhs.photoBytes))
      return false;
    if (__isset.extraList != rhs.__isset.extraList)
      return false;
    else if (__isset.extraList && !(extraList == rhs.extraList))
      return false;
    if (__isset.extraMap != rhs.__isset.extraMap)
      return false;
    else if (__isset.extraMap && !(extraMap == rhs.extraMap))
      return false;
    return true;
  }
  bool operator != (const TimUserBean &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimUserBean & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimUserBean &a, TimUserBean &b);

inline std::ostream& operator<<(std::ostream& out, const TimUserBean& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimRoom__isset {
  _TimRoom__isset() : tid(false), founderTid(false), HostsTid(false), membersTid(false), headurl(false), roomName(false), desc(false), createTime(false), extraList(false), extraMap(false) {}
  bool tid :1;
  bool founderTid :1;
  bool HostsTid :1;
  bool membersTid :1;
  bool headurl :1;
  bool roomName :1;
  bool desc :1;
  bool createTime :1;
  bool extraList :1;
  bool extraMap :1;
} _TimRoom__isset;

class TimRoom {
 public:

  TimRoom(const TimRoom&);
  TimRoom& operator=(const TimRoom&);
  TimRoom() : headurl(), roomName(), desc() {
  }

  virtual ~TimRoom() throw();
  Tid tid;
  Tid founderTid;
  std::vector<Tid>  HostsTid;
  std::vector<Tid>  membersTid;
  std::string headurl;
  std::string roomName;
  std::string desc;
  TimTime createTime;
  std::vector<TimNode>  extraList;
  std::map<std::string, std::string>  extraMap;

  _TimRoom__isset __isset;

  void __set_tid(const Tid& val);

  void __set_founderTid(const Tid& val);

  void __set_HostsTid(const std::vector<Tid> & val);

  void __set_membersTid(const std::vector<Tid> & val);

  void __set_headurl(const std::string& val);

  void __set_roomName(const std::string& val);

  void __set_desc(const std::string& val);

  void __set_createTime(const TimTime& val);

  void __set_extraList(const std::vector<TimNode> & val);

  void __set_extraMap(const std::map<std::string, std::string> & val);

  bool operator == (const TimRoom & rhs) const
  {
    if (__isset.tid != rhs.__isset.tid)
      return false;
    else if (__isset.tid && !(tid == rhs.tid))
      return false;
    if (__isset.founderTid != rhs.__isset.founderTid)
      return false;
    else if (__isset.founderTid && !(founderTid == rhs.founderTid))
      return false;
    if (__isset.HostsTid != rhs.__isset.HostsTid)
      return false;
    else if (__isset.HostsTid && !(HostsTid == rhs.HostsTid))
      return false;
    if (__isset.membersTid != rhs.__isset.membersTid)
      return false;
    else if (__isset.membersTid && !(membersTid == rhs.membersTid))
      return false;
    if (__isset.headurl != rhs.__isset.headurl)
      return false;
    else if (__isset.headurl && !(headurl == rhs.headurl))
      return false;
    if (__isset.roomName != rhs.__isset.roomName)
      return false;
    else if (__isset.roomName && !(roomName == rhs.roomName))
      return false;
    if (__isset.desc != rhs.__isset.desc)
      return false;
    else if (__isset.desc && !(desc == rhs.desc))
      return false;
    if (__isset.createTime != rhs.__isset.createTime)
      return false;
    else if (__isset.createTime && !(createTime == rhs.createTime))
      return false;
    if (__isset.extraList != rhs.__isset.extraList)
      return false;
    else if (__isset.extraList && !(extraList == rhs.extraList))
      return false;
    if (__isset.extraMap != rhs.__isset.extraMap)
      return false;
    else if (__isset.extraMap && !(extraMap == rhs.extraMap))
      return false;
    return true;
  }
  bool operator != (const TimRoom &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimRoom & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimRoom &a, TimRoom &b);

inline std::ostream& operator<<(std::ostream& out, const TimRoom& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimPBean__isset {
  _TimPBean__isset() : fromTid(false), toTid(false), status(false), type(false), priority(false), show(false), leaguerTid(false), extraList(false), error(false), extraMap(false) {}
  bool fromTid :1;
  bool toTid :1;
  bool status :1;
  bool type :1;
  bool priority :1;
  bool show :1;
  bool leaguerTid :1;
  bool extraList :1;
  bool error :1;
  bool extraMap :1;
} _TimPBean__isset;

class TimPBean {
 public:

  TimPBean(const TimPBean&);
  TimPBean& operator=(const TimPBean&);
  TimPBean() : threadId(), status(), type(), priority(0), show() {
  }

  virtual ~TimPBean() throw();
  std::string threadId;
  Tid fromTid;
  Tid toTid;
  std::string status;
  std::string type;
  int32_t priority;
  std::string show;
  Tid leaguerTid;
  std::vector<TimNode>  extraList;
  TimError error;
  std::map<std::string, std::string>  extraMap;

  _TimPBean__isset __isset;

  void __set_threadId(const std::string& val);

  void __set_fromTid(const Tid& val);

  void __set_toTid(const Tid& val);

  void __set_status(const std::string& val);

  void __set_type(const std::string& val);

  void __set_priority(const int32_t val);

  void __set_show(const std::string& val);

  void __set_leaguerTid(const Tid& val);

  void __set_extraList(const std::vector<TimNode> & val);

  void __set_error(const TimError& val);

  void __set_extraMap(const std::map<std::string, std::string> & val);

  bool operator == (const TimPBean & rhs) const
  {
    if (!(threadId == rhs.threadId))
      return false;
    if (__isset.fromTid != rhs.__isset.fromTid)
      return false;
    else if (__isset.fromTid && !(fromTid == rhs.fromTid))
      return false;
    if (__isset.toTid != rhs.__isset.toTid)
      return false;
    else if (__isset.toTid && !(toTid == rhs.toTid))
      return false;
    if (__isset.status != rhs.__isset.status)
      return false;
    else if (__isset.status && !(status == rhs.status))
      return false;
    if (__isset.type != rhs.__isset.type)
      return false;
    else if (__isset.type && !(type == rhs.type))
      return false;
    if (__isset.priority != rhs.__isset.priority)
      return false;
    else if (__isset.priority && !(priority == rhs.priority))
      return false;
    if (__isset.show != rhs.__isset.show)
      return false;
    else if (__isset.show && !(show == rhs.show))
      return false;
    if (__isset.leaguerTid != rhs.__isset.leaguerTid)
      return false;
    else if (__isset.leaguerTid && !(leaguerTid == rhs.leaguerTid))
      return false;
    if (__isset.extraList != rhs.__isset.extraList)
      return false;
    else if (__isset.extraList && !(extraList == rhs.extraList))
      return false;
    if (__isset.error != rhs.__isset.error)
      return false;
    else if (__isset.error && !(error == rhs.error))
      return false;
    if (__isset.extraMap != rhs.__isset.extraMap)
      return false;
    else if (__isset.extraMap && !(extraMap == rhs.extraMap))
      return false;
    return true;
  }
  bool operator != (const TimPBean &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimPBean & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimPBean &a, TimPBean &b);

inline std::ostream& operator<<(std::ostream& out, const TimPBean& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimMBean__isset {
  _TimMBean__isset() : mid(false), fromTid(false), toTid(false), body(false), type(false), msgType(false), offline(false), leaguerTid(false), extraList(false), timestamp(false), error(false), extraMap(false), readstatus(false) {}
  bool mid :1;
  bool fromTid :1;
  bool toTid :1;
  bool body :1;
  bool type :1;
  bool msgType :1;
  bool offline :1;
  bool leaguerTid :1;
  bool extraList :1;
  bool timestamp :1;
  bool error :1;
  bool extraMap :1;
  bool readstatus :1;
} _TimMBean__isset;

class TimMBean {
 public:

  TimMBean(const TimMBean&);
  TimMBean& operator=(const TimMBean&);
  TimMBean() : threadId(), mid(), body(), type(), msgType(0), timestamp(), readstatus(0) {
  }

  virtual ~TimMBean() throw();
  std::string threadId;
  std::string mid;
  Tid fromTid;
  Tid toTid;
  std::string body;
  std::string type;
  int16_t msgType;
  TimTime offline;
  Tid leaguerTid;
  std::vector<TimNode>  extraList;
  std::string timestamp;
  TimError error;
  std::map<std::string, std::string>  extraMap;
  int16_t readstatus;

  _TimMBean__isset __isset;

  void __set_threadId(const std::string& val);

  void __set_mid(const std::string& val);

  void __set_fromTid(const Tid& val);

  void __set_toTid(const Tid& val);

  void __set_body(const std::string& val);

  void __set_type(const std::string& val);

  void __set_msgType(const int16_t val);

  void __set_offline(const TimTime& val);

  void __set_leaguerTid(const Tid& val);

  void __set_extraList(const std::vector<TimNode> & val);

  void __set_timestamp(const std::string& val);

  void __set_error(const TimError& val);

  void __set_extraMap(const std::map<std::string, std::string> & val);

  void __set_readstatus(const int16_t val);

  bool operator == (const TimMBean & rhs) const
  {
    if (!(threadId == rhs.threadId))
      return false;
    if (__isset.mid != rhs.__isset.mid)
      return false;
    else if (__isset.mid && !(mid == rhs.mid))
      return false;
    if (__isset.fromTid != rhs.__isset.fromTid)
      return false;
    else if (__isset.fromTid && !(fromTid == rhs.fromTid))
      return false;
    if (__isset.toTid != rhs.__isset.toTid)
      return false;
    else if (__isset.toTid && !(toTid == rhs.toTid))
      return false;
    if (__isset.body != rhs.__isset.body)
      return false;
    else if (__isset.body && !(body == rhs.body))
      return false;
    if (__isset.type != rhs.__isset.type)
      return false;
    else if (__isset.type && !(type == rhs.type))
      return false;
    if (__isset.msgType != rhs.__isset.msgType)
      return false;
    else if (__isset.msgType && !(msgType == rhs.msgType))
      return false;
    if (__isset.offline != rhs.__isset.offline)
      return false;
    else if (__isset.offline && !(offline == rhs.offline))
      return false;
    if (__isset.leaguerTid != rhs.__isset.leaguerTid)
      return false;
    else if (__isset.leaguerTid && !(leaguerTid == rhs.leaguerTid))
      return false;
    if (__isset.extraList != rhs.__isset.extraList)
      return false;
    else if (__isset.extraList && !(extraList == rhs.extraList))
      return false;
    if (__isset.timestamp != rhs.__isset.timestamp)
      return false;
    else if (__isset.timestamp && !(timestamp == rhs.timestamp))
      return false;
    if (__isset.error != rhs.__isset.error)
      return false;
    else if (__isset.error && !(error == rhs.error))
      return false;
    if (__isset.extraMap != rhs.__isset.extraMap)
      return false;
    else if (__isset.extraMap && !(extraMap == rhs.extraMap))
      return false;
    if (__isset.readstatus != rhs.__isset.readstatus)
      return false;
    else if (__isset.readstatus && !(readstatus == rhs.readstatus))
      return false;
    return true;
  }
  bool operator != (const TimMBean &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimMBean & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimMBean &a, TimMBean &b);

inline std::ostream& operator<<(std::ostream& out, const TimMBean& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimIqBean__isset {
  _TimIqBean__isset() : fromTid(false), toTid(false), type(false), extraList(false), error(false), extraMap(false) {}
  bool fromTid :1;
  bool toTid :1;
  bool type :1;
  bool extraList :1;
  bool error :1;
  bool extraMap :1;
} _TimIqBean__isset;

class TimIqBean {
 public:

  TimIqBean(const TimIqBean&);
  TimIqBean& operator=(const TimIqBean&);
  TimIqBean() : threadId(), type() {
  }

  virtual ~TimIqBean() throw();
  std::string threadId;
  Tid fromTid;
  Tid toTid;
  std::string type;
  std::vector<TimNode>  extraList;
  TimError error;
  std::map<std::string, std::string>  extraMap;

  _TimIqBean__isset __isset;

  void __set_threadId(const std::string& val);

  void __set_fromTid(const Tid& val);

  void __set_toTid(const Tid& val);

  void __set_type(const std::string& val);

  void __set_extraList(const std::vector<TimNode> & val);

  void __set_error(const TimError& val);

  void __set_extraMap(const std::map<std::string, std::string> & val);

  bool operator == (const TimIqBean & rhs) const
  {
    if (!(threadId == rhs.threadId))
      return false;
    if (__isset.fromTid != rhs.__isset.fromTid)
      return false;
    else if (__isset.fromTid && !(fromTid == rhs.fromTid))
      return false;
    if (__isset.toTid != rhs.__isset.toTid)
      return false;
    else if (__isset.toTid && !(toTid == rhs.toTid))
      return false;
    if (__isset.type != rhs.__isset.type)
      return false;
    else if (__isset.type && !(type == rhs.type))
      return false;
    if (__isset.extraList != rhs.__isset.extraList)
      return false;
    else if (__isset.extraList && !(extraList == rhs.extraList))
      return false;
    if (__isset.error != rhs.__isset.error)
      return false;
    else if (__isset.error && !(error == rhs.error))
      return false;
    if (__isset.extraMap != rhs.__isset.extraMap)
      return false;
    else if (__isset.extraMap && !(extraMap == rhs.extraMap))
      return false;
    return true;
  }
  bool operator != (const TimIqBean &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimIqBean & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimIqBean &a, TimIqBean &b);

inline std::ostream& operator<<(std::ostream& out, const TimIqBean& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimRoster__isset {
  _TimRoster__isset() : name(false), extraMap(false) {}
  bool name :1;
  bool extraMap :1;
} _TimRoster__isset;

class TimRoster {
 public:

  TimRoster(const TimRoster&);
  TimRoster& operator=(const TimRoster&);
  TimRoster() : subscription(), name() {
  }

  virtual ~TimRoster() throw();
  std::string subscription;
  Tid tid;
  std::string name;
  std::map<std::string, std::string>  extraMap;

  _TimRoster__isset __isset;

  void __set_subscription(const std::string& val);

  void __set_tid(const Tid& val);

  void __set_name(const std::string& val);

  void __set_extraMap(const std::map<std::string, std::string> & val);

  bool operator == (const TimRoster & rhs) const
  {
    if (!(subscription == rhs.subscription))
      return false;
    if (!(tid == rhs.tid))
      return false;
    if (__isset.name != rhs.__isset.name)
      return false;
    else if (__isset.name && !(name == rhs.name))
      return false;
    if (__isset.extraMap != rhs.__isset.extraMap)
      return false;
    else if (__isset.extraMap && !(extraMap == rhs.extraMap))
      return false;
    return true;
  }
  bool operator != (const TimRoster &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimRoster & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimRoster &a, TimRoster &b);

inline std::ostream& operator<<(std::ostream& out, const TimRoster& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimRemoteUserBean__isset {
  _TimRemoteUserBean__isset() : error(false), ub(false), extraMap(false) {}
  bool error :1;
  bool ub :1;
  bool extraMap :1;
} _TimRemoteUserBean__isset;

class TimRemoteUserBean {
 public:

  TimRemoteUserBean(const TimRemoteUserBean&);
  TimRemoteUserBean& operator=(const TimRemoteUserBean&);
  TimRemoteUserBean() {
  }

  virtual ~TimRemoteUserBean() throw();
  TimError error;
  TimUserBean ub;
  std::map<std::string, std::string>  extraMap;

  _TimRemoteUserBean__isset __isset;

  void __set_error(const TimError& val);

  void __set_ub(const TimUserBean& val);

  void __set_extraMap(const std::map<std::string, std::string> & val);

  bool operator == (const TimRemoteUserBean & rhs) const
  {
    if (__isset.error != rhs.__isset.error)
      return false;
    else if (__isset.error && !(error == rhs.error))
      return false;
    if (__isset.ub != rhs.__isset.ub)
      return false;
    else if (__isset.ub && !(ub == rhs.ub))
      return false;
    if (__isset.extraMap != rhs.__isset.extraMap)
      return false;
    else if (__isset.extraMap && !(extraMap == rhs.extraMap))
      return false;
    return true;
  }
  bool operator != (const TimRemoteUserBean &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimRemoteUserBean & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimRemoteUserBean &a, TimRemoteUserBean &b);

inline std::ostream& operator<<(std::ostream& out, const TimRemoteUserBean& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimRemoteRoom__isset {
  _TimRemoteRoom__isset() : error(false), room(false), extraMap(false) {}
  bool error :1;
  bool room :1;
  bool extraMap :1;
} _TimRemoteRoom__isset;

class TimRemoteRoom {
 public:

  TimRemoteRoom(const TimRemoteRoom&);
  TimRemoteRoom& operator=(const TimRemoteRoom&);
  TimRemoteRoom() {
  }

  virtual ~TimRemoteRoom() throw();
  TimError error;
  TimRoom room;
  std::map<std::string, std::string>  extraMap;

  _TimRemoteRoom__isset __isset;

  void __set_error(const TimError& val);

  void __set_room(const TimRoom& val);

  void __set_extraMap(const std::map<std::string, std::string> & val);

  bool operator == (const TimRemoteRoom & rhs) const
  {
    if (__isset.error != rhs.__isset.error)
      return false;
    else if (__isset.error && !(error == rhs.error))
      return false;
    if (__isset.room != rhs.__isset.room)
      return false;
    else if (__isset.room && !(room == rhs.room))
      return false;
    if (__isset.extraMap != rhs.__isset.extraMap)
      return false;
    else if (__isset.extraMap && !(extraMap == rhs.extraMap))
      return false;
    return true;
  }
  bool operator != (const TimRemoteRoom &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimRemoteRoom & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimRemoteRoom &a, TimRemoteRoom &b);

inline std::ostream& operator<<(std::ostream& out, const TimRemoteRoom& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimResponseBean__isset {
  _TimResponseBean__isset() : threadId(false), error(false), extraList(false), extraMap(false) {}
  bool threadId :1;
  bool error :1;
  bool extraList :1;
  bool extraMap :1;
} _TimResponseBean__isset;

class TimResponseBean {
 public:

  TimResponseBean(const TimResponseBean&);
  TimResponseBean& operator=(const TimResponseBean&);
  TimResponseBean() : threadId() {
  }

  virtual ~TimResponseBean() throw();
  std::string threadId;
  TimError error;
  std::vector<TimNode>  extraList;
  std::map<std::string, std::string>  extraMap;

  _TimResponseBean__isset __isset;

  void __set_threadId(const std::string& val);

  void __set_error(const TimError& val);

  void __set_extraList(const std::vector<TimNode> & val);

  void __set_extraMap(const std::map<std::string, std::string> & val);

  bool operator == (const TimResponseBean & rhs) const
  {
    if (__isset.threadId != rhs.__isset.threadId)
      return false;
    else if (__isset.threadId && !(threadId == rhs.threadId))
      return false;
    if (__isset.error != rhs.__isset.error)
      return false;
    else if (__isset.error && !(error == rhs.error))
      return false;
    if (__isset.extraList != rhs.__isset.extraList)
      return false;
    else if (__isset.extraList && !(extraList == rhs.extraList))
      return false;
    if (__isset.extraMap != rhs.__isset.extraMap)
      return false;
    else if (__isset.extraMap && !(extraMap == rhs.extraMap))
      return false;
    return true;
  }
  bool operator != (const TimResponseBean &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimResponseBean & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimResponseBean &a, TimResponseBean &b);

inline std::ostream& operator<<(std::ostream& out, const TimResponseBean& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimSock5Bean__isset {
  _TimSock5Bean__isset() : extraMap(false) {}
  bool extraMap :1;
} _TimSock5Bean__isset;

class TimSock5Bean {
 public:

  TimSock5Bean(const TimSock5Bean&);
  TimSock5Bean& operator=(const TimSock5Bean&);
  TimSock5Bean() : addr(), port(0), transport(0), pubId() {
  }

  virtual ~TimSock5Bean() throw();
  Tid fromTid;
  Tid toTid;
  std::string addr;
  int32_t port;
  int16_t transport;
  std::string pubId;
  std::map<std::string, std::string>  extraMap;

  _TimSock5Bean__isset __isset;

  void __set_fromTid(const Tid& val);

  void __set_toTid(const Tid& val);

  void __set_addr(const std::string& val);

  void __set_port(const int32_t val);

  void __set_transport(const int16_t val);

  void __set_pubId(const std::string& val);

  void __set_extraMap(const std::map<std::string, std::string> & val);

  bool operator == (const TimSock5Bean & rhs) const
  {
    if (!(fromTid == rhs.fromTid))
      return false;
    if (!(toTid == rhs.toTid))
      return false;
    if (!(addr == rhs.addr))
      return false;
    if (!(port == rhs.port))
      return false;
    if (!(transport == rhs.transport))
      return false;
    if (!(pubId == rhs.pubId))
      return false;
    if (__isset.extraMap != rhs.__isset.extraMap)
      return false;
    else if (__isset.extraMap && !(extraMap == rhs.extraMap))
      return false;
    return true;
  }
  bool operator != (const TimSock5Bean &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimSock5Bean & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimSock5Bean &a, TimSock5Bean &b);

inline std::ostream& operator<<(std::ostream& out, const TimSock5Bean& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimSock5Bytes__isset {
  _TimSock5Bytes__isset() : extraMap(false) {}
  bool extraMap :1;
} _TimSock5Bytes__isset;

class TimSock5Bytes {
 public:

  TimSock5Bytes(const TimSock5Bytes&);
  TimSock5Bytes& operator=(const TimSock5Bytes&);
  TimSock5Bytes() : pubId(), index(0) {
  }

  virtual ~TimSock5Bytes() throw();
  std::string pubId;
  int32_t index;
  std::vector<std::string>  bytes;
  std::map<std::string, std::string>  extraMap;

  _TimSock5Bytes__isset __isset;

  void __set_pubId(const std::string& val);

  void __set_index(const int32_t val);

  void __set_bytes(const std::vector<std::string> & val);

  void __set_extraMap(const std::map<std::string, std::string> & val);

  bool operator == (const TimSock5Bytes & rhs) const
  {
    if (!(pubId == rhs.pubId))
      return false;
    if (!(index == rhs.index))
      return false;
    if (!(bytes == rhs.bytes))
      return false;
    if (__isset.extraMap != rhs.__isset.extraMap)
      return false;
    else if (__isset.extraMap && !(extraMap == rhs.extraMap))
      return false;
    return true;
  }
  bool operator != (const TimSock5Bytes &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimSock5Bytes & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimSock5Bytes &a, TimSock5Bytes &b);

inline std::ostream& operator<<(std::ostream& out, const TimSock5Bytes& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimPage__isset {
  _TimPage__isset() : fromTimeStamp(false), toTimeStamp(false), limitCount(false), extraMap(false) {}
  bool fromTimeStamp :1;
  bool toTimeStamp :1;
  bool limitCount :1;
  bool extraMap :1;
} _TimPage__isset;

class TimPage {
 public:

  TimPage(const TimPage&);
  TimPage& operator=(const TimPage&);
  TimPage() : fromTimeStamp(), toTimeStamp(), limitCount(0) {
  }

  virtual ~TimPage() throw();
  std::string fromTimeStamp;
  std::string toTimeStamp;
  int32_t limitCount;
  std::map<std::string, std::string>  extraMap;

  _TimPage__isset __isset;

  void __set_fromTimeStamp(const std::string& val);

  void __set_toTimeStamp(const std::string& val);

  void __set_limitCount(const int32_t val);

  void __set_extraMap(const std::map<std::string, std::string> & val);

  bool operator == (const TimPage & rhs) const
  {
    if (__isset.fromTimeStamp != rhs.__isset.fromTimeStamp)
      return false;
    else if (__isset.fromTimeStamp && !(fromTimeStamp == rhs.fromTimeStamp))
      return false;
    if (__isset.toTimeStamp != rhs.__isset.toTimeStamp)
      return false;
    else if (__isset.toTimeStamp && !(toTimeStamp == rhs.toTimeStamp))
      return false;
    if (__isset.limitCount != rhs.__isset.limitCount)
      return false;
    else if (__isset.limitCount && !(limitCount == rhs.limitCount))
      return false;
    if (__isset.extraMap != rhs.__isset.extraMap)
      return false;
    else if (__isset.extraMap && !(extraMap == rhs.extraMap))
      return false;
    return true;
  }
  bool operator != (const TimPage &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimPage & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimPage &a, TimPage &b);

inline std::ostream& operator<<(std::ostream& out, const TimPage& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimMessageIq__isset {
  _TimMessageIq__isset() : tidlist(false), timPage(false), midlist(false), extraMap(false) {}
  bool tidlist :1;
  bool timPage :1;
  bool midlist :1;
  bool extraMap :1;
} _TimMessageIq__isset;

class TimMessageIq {
 public:

  TimMessageIq(const TimMessageIq&);
  TimMessageIq& operator=(const TimMessageIq&);
  TimMessageIq() {
  }

  virtual ~TimMessageIq() throw();
  std::vector<std::string>  tidlist;
  TimPage timPage;
  std::vector<std::string>  midlist;
  std::map<std::string, std::string>  extraMap;

  _TimMessageIq__isset __isset;

  void __set_tidlist(const std::vector<std::string> & val);

  void __set_timPage(const TimPage& val);

  void __set_midlist(const std::vector<std::string> & val);

  void __set_extraMap(const std::map<std::string, std::string> & val);

  bool operator == (const TimMessageIq & rhs) const
  {
    if (__isset.tidlist != rhs.__isset.tidlist)
      return false;
    else if (__isset.tidlist && !(tidlist == rhs.tidlist))
      return false;
    if (__isset.timPage != rhs.__isset.timPage)
      return false;
    else if (__isset.timPage && !(timPage == rhs.timPage))
      return false;
    if (__isset.midlist != rhs.__isset.midlist)
      return false;
    else if (__isset.midlist && !(midlist == rhs.midlist))
      return false;
    if (__isset.extraMap != rhs.__isset.extraMap)
      return false;
    else if (__isset.extraMap && !(extraMap == rhs.extraMap))
      return false;
    return true;
  }
  bool operator != (const TimMessageIq &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimMessageIq & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimMessageIq &a, TimMessageIq &b);

inline std::ostream& operator<<(std::ostream& out, const TimMessageIq& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimAuth__isset {
  _TimAuth__isset() : domain(false), username(false), pwd(false) {}
  bool domain :1;
  bool username :1;
  bool pwd :1;
} _TimAuth__isset;

class TimAuth {
 public:

  TimAuth(const TimAuth&);
  TimAuth& operator=(const TimAuth&);
  TimAuth() : domain(), username(), pwd() {
  }

  virtual ~TimAuth() throw();
  std::string domain;
  std::string username;
  std::string pwd;

  _TimAuth__isset __isset;

  void __set_domain(const std::string& val);

  void __set_username(const std::string& val);

  void __set_pwd(const std::string& val);

  bool operator == (const TimAuth & rhs) const
  {
    if (__isset.domain != rhs.__isset.domain)
      return false;
    else if (__isset.domain && !(domain == rhs.domain))
      return false;
    if (__isset.username != rhs.__isset.username)
      return false;
    else if (__isset.username && !(username == rhs.username))
      return false;
    if (__isset.pwd != rhs.__isset.pwd)
      return false;
    else if (__isset.pwd && !(pwd == rhs.pwd))
      return false;
    return true;
  }
  bool operator != (const TimAuth &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimAuth & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimAuth &a, TimAuth &b);

inline std::ostream& operator<<(std::ostream& out, const TimAuth& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimMBeanList__isset {
  _TimMBeanList__isset() : timMBeanList(false), reqType(false), extraMap(false) {}
  bool timMBeanList :1;
  bool reqType :1;
  bool extraMap :1;
} _TimMBeanList__isset;

class TimMBeanList {
 public:

  TimMBeanList(const TimMBeanList&);
  TimMBeanList& operator=(const TimMBeanList&);
  TimMBeanList() : threadId(), reqType() {
  }

  virtual ~TimMBeanList() throw();
  std::string threadId;
  std::vector<TimMBean>  timMBeanList;
  std::string reqType;
  std::map<std::string, std::string>  extraMap;

  _TimMBeanList__isset __isset;

  void __set_threadId(const std::string& val);

  void __set_timMBeanList(const std::vector<TimMBean> & val);

  void __set_reqType(const std::string& val);

  void __set_extraMap(const std::map<std::string, std::string> & val);

  bool operator == (const TimMBeanList & rhs) const
  {
    if (!(threadId == rhs.threadId))
      return false;
    if (__isset.timMBeanList != rhs.__isset.timMBeanList)
      return false;
    else if (__isset.timMBeanList && !(timMBeanList == rhs.timMBeanList))
      return false;
    if (__isset.reqType != rhs.__isset.reqType)
      return false;
    else if (__isset.reqType && !(reqType == rhs.reqType))
      return false;
    if (__isset.extraMap != rhs.__isset.extraMap)
      return false;
    else if (__isset.extraMap && !(extraMap == rhs.extraMap))
      return false;
    return true;
  }
  bool operator != (const TimMBeanList &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimMBeanList & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimMBeanList &a, TimMBeanList &b);

inline std::ostream& operator<<(std::ostream& out, const TimMBeanList& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimPBeanList__isset {
  _TimPBeanList__isset() : timPBeanList(false), reqType(false), extraMap(false) {}
  bool timPBeanList :1;
  bool reqType :1;
  bool extraMap :1;
} _TimPBeanList__isset;

class TimPBeanList {
 public:

  TimPBeanList(const TimPBeanList&);
  TimPBeanList& operator=(const TimPBeanList&);
  TimPBeanList() : threadId(), reqType() {
  }

  virtual ~TimPBeanList() throw();
  std::string threadId;
  std::vector<TimPBean>  timPBeanList;
  std::string reqType;
  std::map<std::string, std::string>  extraMap;

  _TimPBeanList__isset __isset;

  void __set_threadId(const std::string& val);

  void __set_timPBeanList(const std::vector<TimPBean> & val);

  void __set_reqType(const std::string& val);

  void __set_extraMap(const std::map<std::string, std::string> & val);

  bool operator == (const TimPBeanList & rhs) const
  {
    if (!(threadId == rhs.threadId))
      return false;
    if (__isset.timPBeanList != rhs.__isset.timPBeanList)
      return false;
    else if (__isset.timPBeanList && !(timPBeanList == rhs.timPBeanList))
      return false;
    if (__isset.reqType != rhs.__isset.reqType)
      return false;
    else if (__isset.reqType && !(reqType == rhs.reqType))
      return false;
    if (__isset.extraMap != rhs.__isset.extraMap)
      return false;
    else if (__isset.extraMap && !(extraMap == rhs.extraMap))
      return false;
    return true;
  }
  bool operator != (const TimPBeanList &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimPBeanList & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimPBeanList &a, TimPBeanList &b);

inline std::ostream& operator<<(std::ostream& out, const TimPBeanList& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TimPropertyBean__isset {
  _TimPropertyBean__isset() : threadId(false), interflow(false), tls(false) {}
  bool threadId :1;
  bool interflow :1;
  bool tls :1;
} _TimPropertyBean__isset;

class TimPropertyBean {
 public:

  TimPropertyBean(const TimPropertyBean&);
  TimPropertyBean& operator=(const TimPropertyBean&);
  TimPropertyBean() : threadId(), interflow(), tls() {
  }

  virtual ~TimPropertyBean() throw();
  std::string threadId;
  std::string interflow;
  std::string tls;

  _TimPropertyBean__isset __isset;

  void __set_threadId(const std::string& val);

  void __set_interflow(const std::string& val);

  void __set_tls(const std::string& val);

  bool operator == (const TimPropertyBean & rhs) const
  {
    if (__isset.threadId != rhs.__isset.threadId)
      return false;
    else if (__isset.threadId && !(threadId == rhs.threadId))
      return false;
    if (__isset.interflow != rhs.__isset.interflow)
      return false;
    else if (__isset.interflow && !(interflow == rhs.interflow))
      return false;
    if (__isset.tls != rhs.__isset.tls)
      return false;
    else if (__isset.tls && !(tls == rhs.tls))
      return false;
    return true;
  }
  bool operator != (const TimPropertyBean &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimPropertyBean & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimPropertyBean &a, TimPropertyBean &b);

inline std::ostream& operator<<(std::ostream& out, const TimPropertyBean& obj)
{
  obj.printTo(out);
  return out;
}



#endif
